<?php
declare(strict_types=1);
namespace WordPressNewsBot\Tests;
use WordPressNewsBot\FeedParser;use PHPUnit\Framework\TestCase;
final class FeedParserTest extends TestCase
{
    public function testParsesRssWithoutNetwork():void{$items=(new FeedParser())->parse('<rss><channel><item><guid>abc</guid><title>News</title><link>https://example.com/news?utm_source=x</link><description>Summary</description></item></channel></rss>');$this->assertSame('abc',$items[0]['guid']);$this->assertSame('News',$items[0]['title']);}
    public function testRejectsMalformedFeed():void{$this->expectException(\RuntimeException::class);(new FeedParser())->parse('<rss>');}
    public function testParsesSourceCategory():void{$items=(new FeedParser())->parse('<rss><channel><item><guid>1</guid><title>One</title><link>https://example.com/1</link><category>World</category></item></channel></rss>');$this->assertSame('World',$items[0]['source_category']);}
    public function testParsesDeclaredNonUtf8XmlEncoding():void{$xml='<?xml version="1.0" encoding="ISO-8859-1"?><rss><channel><item><guid>1</guid><title>Caf'.chr(233).'</title><link>https://example.com/n</link></item></channel></rss>';$items=(new FeedParser())->parse($xml);$this->assertSame('Café',$items[0]['title']);}
    public function testUsesMediaContentBeforeThumbnailEnclosureAndHtml():void{$xml='<rss xmlns:media="http://search.yahoo.com/mrss/"><channel><item><guid>1</guid><title>One</title><link>https://example.com/1</link><media:content url="https://cdn.example.com/content.jpg" type="image/jpeg"/><media:thumbnail url="https://cdn.example.com/thumb.jpg"/><enclosure url="https://cdn.example.com/enclosure.jpg" type="image/jpeg"/><description><![CDATA[<img src="https://cdn.example.com/html.jpg">]]></description></item></channel></rss>';$item=(new FeedParser())->parse($xml)[0];$this->assertSame('https://cdn.example.com/content.jpg',$item['image_url']);$this->assertSame('media:content',$item['image_source']);}
    public function testUsesMediaThumbnailThenImageEnclosure():void{$thumbnail='<rss xmlns:media="http://search.yahoo.com/mrss/"><channel><item><guid>1</guid><title>One</title><link>https://example.com/1</link><media:thumbnail url="https://cdn.example.com/thumb.png"/></item></channel></rss>';$item=(new FeedParser())->parse($thumbnail)[0];$this->assertSame('media:thumbnail',$item['image_source']);$enclosure='<rss><channel><item><guid>2</guid><title>Two</title><link>https://example.com/2</link><enclosure url="https://cdn.example.com/two.webp" type="image/webp"/></item></channel></rss>';$item=(new FeedParser())->parse($enclosure)[0];$this->assertSame('enclosure',$item['image_source']);}
    public function testParsesAtomMediaAndHtmlFallback():void{$atom='<feed xmlns="http://www.w3.org/2005/Atom" xmlns:media="http://search.yahoo.com/mrss/"><entry><id>1</id><title>Atom</title><link href="https://example.com/a"/><media:content url="https://cdn.example.com/a.jpg" medium="image"/></entry></feed>';$item=(new FeedParser())->parse($atom)[0];$this->assertSame('media:content',$item['image_source']);$html='<rss><channel><item><guid>3</guid><title>Three</title><link>https://example.com/3</link><description><![CDATA[<p>x</p><img src="https://cdn.example.com/three.png?sig=secret">]]></description></item></channel></rss>';$item=(new FeedParser())->parse($html)[0];$this->assertSame('html:img',$item['image_source']);$this->assertSame('https://cdn.example.com/three.png?sig=secret',$item['image_url']);}
    public function testFindsImageInContentWhenDescriptionHasNone():void{$xml='<rss xmlns:content="http://purl.org/rss/1.0/modules/content/"><channel><item><guid>4</guid><title>Four</title><link>https://example.com/4</link><description>Plain summary</description><content:encoded><![CDATA[<img src="https://cdn.example.com/content.png">]]></content:encoded></item></channel></rss>';$item=(new FeedParser())->parse($xml)[0];$this->assertSame('https://cdn.example.com/content.png',$item['image_url']);}
}
