<?php
declare(strict_types=1);
namespace WordPressNewsBot\Tests;

use DomainException;
use PHPUnit\Framework\TestCase;
use WordPressNewsBot\DatabaseHealth;
use WordPressNewsBot\DatabaseEngineRepair;
use WordPressNewsBot\DatabaseEngineRepairException;
use WordPressNewsBot\DatabaseRepair;
use WordPressNewsBot\DatabaseSchema;
use WordPressNewsBot\SourceService;

final class MariaDbUpgradeIntegrationTest extends TestCase
{
    private MariaDbWpdb $db;
    protected function setUp():void{$db=MariaDbWpdb::connectFromEnvironment();if(!$db)$this->markTestSkipped('WPNB_TEST_DB_DSN is not configured.');$this->db=$db;global$wpdb;$wpdb=$db;$db->reset();$GLOBALS['wpnb_test_options']=[];}
    protected function tearDown():void{if(isset($this->db))$this->db->reset();}

    public function testCleanInstallUsesExplicitInnoDbWhenServerDefaultIsMyIsamAndSecondRepairIsIdempotent():void{$this->db->query('SET SESSION default_storage_engine=MyISAM');$first=(new DatabaseRepair($this->db))->run(true);$second=(new DatabaseRepair($this->db))->run(true);$this->assertSame('healthy',$first['status']);$this->assertGreaterThan(0,$first['changed']);foreach(array_keys(DatabaseSchema::tables())as$logical)$this->assertSame('innodb',strtolower($this->engine($logical)));$this->assertSame('healthy',$second['status']);$this->assertSame(0,$second['changed']);$this->assertSame(WPNB_SCHEMA_VERSION,get_option('wpnb_schema_version'));}

    public function test030UpgradeAddsMissingColumnsAndPreservesSource():void{$this->legacySources();$this->db->insert($this->db->prefix.'wpnb_sources',['name'=>'NTV','feed_url'=>'https://www.ntv.com.tr/tr/turkiye.rss','active'=>1,'category_id'=>0,'allowed_domains'=>'www.ntv.com.tr','created_at'=>'2026-01-01 00:00:00','updated_at'=>'2026-01-01 00:00:00']);update_option('wpnb_schema_version','1.2.0');$result=(new DatabaseRepair($this->db))->run(false);$this->assertSame('healthy',$result['status']);$row=$this->db->get_row('SELECT * FROM `'.$this->db->prefix.'wpnb_sources` LIMIT 1',ARRAY_A);$this->assertSame('NTV',$row['name']);$this->assertSame(hash('sha256','https://www.ntv.com.tr/tr/turkiye.rss'),$row['canonical_hash']);$this->assertArrayHasKey('last_checked_at',$row);}

    public function testAutomaticUpgradeRecoversDuplicateMigrationAndCreatesUniqueIndex():void{$this->legacySources();foreach(['https://example.com/feed','HTTPS://example.com:443/feed/']as$i=>$url)$this->db->insert($this->db->prefix.'wpnb_sources',['name'=>'D'.($i+1),'feed_url'=>$url,'active'=>1,'category_id'=>0,'allowed_domains'=>'example.com','created_at'=>'2026-01-0'.($i+1).' 00:00:00','updated_at'=>'2026-01-01 00:00:00']);update_option('wpnb_schema_version','1.3.0');$result=(new DatabaseRepair($this->db))->run(true);$this->assertSame('healthy',$result['status']);$this->assertSame(1,(int)$this->db->get_var('SELECT COUNT(*) FROM `'.$this->db->prefix.'wpnb_sources`'));$this->assertNotNull($this->db->get_var("SHOW INDEX FROM `{$this->db->prefix}wpnb_sources` WHERE Key_name='canonical_hash_unique'"));}

    public function testEmptyAndHalfFinishedSchemasRepairButUnsafeTypeChangeIsBlocked():void{$this->legacySources();$empty=(new DatabaseRepair($this->db))->run(false);$this->assertSame('healthy',$empty['status']);$this->db->reset();$this->db->query('CREATE TABLE `'.$this->db->prefix."wpnb_sources` (`id` bigint unsigned NOT NULL AUTO_INCREMENT,`name` text NOT NULL,`feed_url` text NOT NULL,`created_at` datetime NOT NULL,`updated_at` datetime NOT NULL,PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");$blocked=(new DatabaseRepair($this->db))->run(false);$this->assertSame('repair_required',$blocked['status']);$codes=array_column($blocked['issues'],'code');$this->assertContains('column_type_mismatch',$codes);}

    public function testLegacyPrefixIndexesAreDetectedAndRebuiltFromCanonicalSchema():void{(new DatabaseRepair($this->db))->run(true);$table=$this->db->prefix.'wpnb_feed_items';$this->db->query("ALTER TABLE `$table` DROP INDEX `source_guid`, ADD UNIQUE INDEX `source_guid` (`source_id`,`guid`(191)), DROP INDEX `normalized_url`, ADD INDEX `normalized_url` (`normalized_url`(191))");$before=(new DatabaseHealth($this->db))->inspect();$this->assertSame(['index_mismatch','index_mismatch'],array_values(array_map(static fn(array$i):string=>$i['code'],array_filter($before['issues'],static fn(array$i):bool=>($i['table']??'')==='feed_items'))));$result=(new DatabaseRepair($this->db))->run(false);$this->assertSame('healthy',$result['status']);$indexes=$this->db->get_results("SHOW INDEX FROM `$table`",ARRAY_A);foreach($indexes as$index)if(in_array($index['Key_name'],['source_guid','normalized_url'],true))$this->assertNull($index['Sub_part']);}

    public function testVerifiedNtvLikeTokenInsertsOnceAndDuplicateGetsSpecificException():void{(new DatabaseRepair($this->db))->run(true);$service=new SourceService($this->db);$input=['name'=>'NTV','feed_url'=>'https://www.ntv.com.tr/tr/turkiye.rss','allowed_domains'=>'www.ntv.com.tr','category_id'=>4,'active'=>1];$verified=['test_id'=>'0e4828f44c90f0af','http_status'=>200,'feed_type'=>'Atom','item_count'=>20,'duration_ms'=>162];$id=$service->save($input,0,$verified);$this->assertGreaterThan(0,$id);$this->assertSame(1,(int)$this->db->get_var('SELECT COUNT(*) FROM `'.$this->db->prefix.'wpnb_sources`'));$this->expectException(DomainException::class);$service->save($input,0,$verified);}

    public function testEightMyIsamTablesConvertWithRelatedDataRowsAndChecksumsPreserved():void{$this->allMyIsamTables();$this->seedRelatedRows();$before=[];foreach(['sources','feed_items','jobs','ai_generations','daily_usage']as$logical)$before[$logical]=[$this->tableCount($logical),$this->checksum($logical)];$this->db->query('CREATE TABLE `'.$this->db->prefix.'unrelated` (`id` int NOT NULL PRIMARY KEY) ENGINE=MyISAM');$result=(new DatabaseRepair($this->db))->run(false,true);$this->assertSame('healthy',$result['status']);$this->assertSame(9,$result['changed'],'Eight engine conversions plus the MyISAM-truncated GUID index repair are required.');foreach(array_keys(DatabaseSchema::tables())as$logical)$this->assertSame('innodb',strtolower($this->engine($logical)));$state=DatabaseEngineRepair::state();foreach(array_keys(DatabaseSchema::tables())as$logical){$conversion=$state['tables'][$logical];$this->assertSame($conversion['rows_before'],$conversion['rows_after'],$logical.' row count changed during ALTER');$this->assertSame($conversion['checksum_before'],$conversion['checksum_after'],$logical.' checksum changed during ALTER');}$this->assertSame($before['sources'],[$this->tableCount('sources'),$this->checksum('sources')]);$this->assertSame($before['feed_items'],[$this->tableCount('feed_items'),$this->checksum('feed_items')]);$this->assertSame($before['jobs'],[$this->tableCount('jobs'),$this->checksum('jobs')]);$this->assertSame(1,(int)$this->db->get_var("SELECT COUNT(*) FROM `{$this->db->prefix}wpnb_logs` WHERE event='seed'"));$this->assertSame('myisam',strtolower((string)($this->db->get_row($this->db->prepare('SHOW TABLE STATUS LIKE %s',$this->db->prefix.'unrelated'),ARRAY_A)['Engine']??'')));$second=(new DatabaseRepair($this->db))->run(false,true);$this->assertSame(0,$second['changed']);}

    public function testFailedAlterStopsLaterTablesAndRerunContinuesFromPartialConversion():void{$this->allMyIsamTables();$this->seedRelatedRows();$this->db->failAlterTable='jobs';try{(new DatabaseRepair($this->db))->run(false,true);$this->fail('Expected conversion failure.');}catch(DatabaseEngineRepairException$e){$this->assertSame('alter_permission_denied',$e->resultCode);}$this->assertSame('innodb',strtolower($this->engine('migration_journal')));$this->assertSame('innodb',strtolower($this->engine('sources')));$this->assertSame('innodb',strtolower($this->engine('feed_items')));$this->assertSame('myisam',strtolower($this->engine('jobs')));$this->assertSame(1,$this->tableCount('jobs'));$this->assertSame('myisam',strtolower($this->engine('ai_generations')));$this->db->failAlterTable='';$resumed=(new DatabaseRepair($this->db))->run(false,true);$this->assertSame('healthy',$resumed['status']);$this->assertSame(6,$resumed['changed'],'Five remaining engine conversions plus the canonical GUID index repair are required.');$this->assertSame(1,$this->tableCount('jobs'));}

    public function testInnoDbUnavailableAndAlterPermissionAreClassifiedBeforeDdl():void{$this->allMyIsamTables();$engine=new DatabaseEngineRepair($this->db);$this->db->simulateInnoDbUnavailable=true;$this->assertSame('innodb_unavailable',$engine->preview()['code']);try{$engine->convert();$this->fail();}catch(DatabaseEngineRepairException$e){$this->assertSame('innodb_unavailable',$e->resultCode);}$this->db->simulateInnoDbUnavailable=false;$this->db->simulateAlterDenied=true;$this->assertSame('alter_permission_denied',$engine->preview()['code']);try{$engine->convert();$this->fail();}catch(DatabaseEngineRepairException$e){$this->assertSame('alter_permission_denied',$e->resultCode);}$this->assertSame([],array_values(array_filter($this->db->queries,static fn(string$sql):bool=>str_starts_with($sql,'ALTER TABLE'))));}

    public function testNtvVerifiedTokenInsertsAfterMyIsamRepairAndDuplicateProtectionRemains():void{$this->allMyIsamTables();update_option('wpnb_source_recovery_required',['reason'=>'engine']);$repair=(new DatabaseRepair($this->db))->run(false,true);$this->assertSame('healthy',$repair['status']);$this->assertFalse(get_option('wpnb_source_recovery_required',false));$service=new SourceService($this->db);$input=['name'=>'NTV','feed_url'=>'https://www.ntv.com.tr/tr/turkiye.rss','allowed_domains'=>'www.ntv.com.tr','category_id'=>4,'active'=>1];$verified=['test_id'=>'8765e8ef90399ed1','http_status'=>200,'feed_type'=>'Atom','item_count'=>20,'duration_ms'=>162];$id=$service->save($input,0,$verified);$this->assertGreaterThan(0,$id);$this->assertSame(1,$this->tableCount('sources'));$this->assertSame($id,(int)$this->db->get_var('SELECT id FROM `'.$this->db->prefix.'wpnb_sources` WHERE name=\'NTV\''));$this->expectException(DomainException::class);$service->save($input,0,$verified);}

    private function legacySources():void{$this->db->query('CREATE TABLE `'.$this->db->prefix."wpnb_sources` (`id` bigint unsigned NOT NULL AUTO_INCREMENT,`name` varchar(190) NOT NULL,`feed_url` text NOT NULL,`active` tinyint NOT NULL DEFAULT 1,`category_id` bigint unsigned NOT NULL DEFAULT 0,`allowed_domains` text NULL,`created_at` datetime NOT NULL,`updated_at` datetime NOT NULL,PRIMARY KEY (`id`),KEY `active` (`active`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");}
    private function allMyIsamTables():void{foreach(array_keys(DatabaseSchema::tables())as$logical){$sql=str_replace('ENGINE=InnoDB','ENGINE=MyISAM',DatabaseSchema::createSql($logical,$this->db->get_charset_collate()));$this->db->query($sql);}}
    private function seedRelatedRows():void{$now='2026-08-13 12:00:00';$this->db->insert($this->db->prefix.'wpnb_sources',['name'=>'NTV','feed_url'=>'https://www.ntv.com.tr/tr/turkiye.rss','canonical_hash'=>hash('sha256','https://www.ntv.com.tr/tr/turkiye.rss'),'allowed_domains'=>'www.ntv.com.tr','created_at'=>$now,'updated_at'=>$now]);$source=(int)$this->db->insert_id;$this->db->insert($this->db->prefix.'wpnb_feed_items',['source_id'=>$source,'source_name'=>'NTV','source_feed_url'=>'https://www.ntv.com.tr/tr/turkiye.rss','guid'=>'ntv-1','source_url'=>'https://www.ntv.com.tr/haber','normalized_url'=>'https://www.ntv.com.tr/haber','title'=>'Haber','created_at'=>$now,'updated_at'=>$now]);$item=(int)$this->db->insert_id;$this->db->insert($this->db->prefix.'wpnb_jobs',['feed_item_id'=>$item,'type'=>'draft','created_at'=>$now,'updated_at'=>$now]);$this->db->insert($this->db->prefix.'wpnb_ai_generations',['feed_item_id'=>$item,'provider'=>'openai','model'=>'test','output_json'=>'{}','created_at'=>$now]);$this->db->insert($this->db->prefix.'wpnb_logs',['level'=>'info','event'=>'seed','message'=>'safe','created_at'=>$now]);$this->db->insert($this->db->prefix.'wpnb_daily_usage',['usage_date'=>'2026-08-13']);}
    private function engine(string$logical):string{return(string)($this->db->get_row($this->db->prepare('SHOW TABLE STATUS LIKE %s',$this->db->prefix.'wpnb_'.$logical),ARRAY_A)['Engine']??'');}
    private function tableCount(string$logical):int{return(int)$this->db->get_var('SELECT COUNT(*) FROM `'.$this->db->prefix.'wpnb_'.$logical.'`');}
    private function checksum(string$logical):?string{$row=$this->db->get_row('CHECKSUM TABLE `'.$this->db->prefix.'wpnb_'.$logical.'` EXTENDED',ARRAY_A);return isset($row['Checksum'])?(string)$row['Checksum']:null;}
}
