<?php
if(!defined('ABSPATH'))exit(1);global$wpdb;
$columns=static function(string$table)use($wpdb):array{return array_column((array)$wpdb->get_results('SHOW COLUMNS FROM `'.str_replace('`','``',$table).'`',ARRAY_A),'Field');};
$insert=static function(string$table,array$data)use($wpdb,$columns):int{$allowed=array_flip($columns($table));$data=array_intersect_key($data,$allowed);if($wpdb->insert($table,$data)===false)throw new RuntimeException('seed insert failed: '.$table);return(int)$wpdb->insert_id;};
$now=gmdate('Y-m-d H:i:s');$sources=$wpdb->prefix.'wpnb_sources';$items=$wpdb->prefix.'wpnb_feed_items';$sourceData=['name'=>'Fixture source','feed_url'=>'https://feed.test/rss.xml','canonical_hash'=>'','active'=>1,'category_id'=>0,'daily_quota'=>10,'interval_minutes'=>60,'reliability'=>'medium','author_id'=>1,'post_status'=>'draft','show_attribution'=>1,'allowed_domains'=>'feed.test','created_at'=>$now,'updated_at'=>$now];
if($wpdb->get_var("SHOW INDEX FROM `".str_replace('`','``',$sources)."` WHERE Key_name='canonical_hash_unique'"))$wpdb->query('ALTER TABLE `'.str_replace('`','``',$sources).'` DROP INDEX canonical_hash_unique');$source1=$insert($sources,$sourceData);$source2=$insert($sources,array_replace($sourceData,['name'=>'Duplicate fixture']));
$itemData=['source_id'=>$source1,'source_name'=>'Fixture source','source_feed_url'=>'https://feed.test/rss.xml','guid'=>'upgrade-1','source_url'=>'https://feed.test/items/upgrade-1','normalized_url'=>'https://feed.test/items/upgrade-1','title'=>'Anonymous upgrade item','excerpt'=>'Fixture','content_hash'=>hash('sha256','upgrade-1'),'published_at'=>$now,'status'=>'new','raw_data'=>null,'created_at'=>$now,'updated_at'=>$now];$item1=$insert($items,$itemData);$item2=$insert($items,array_replace($itemData,['source_id'=>$source2,'guid'=>'upgrade-2','source_url'=>'https://feed.test/items/upgrade-2','normalized_url'=>'https://feed.test/items/upgrade-2','content_hash'=>hash('sha256','upgrade-2')]));
$insert($wpdb->prefix.'wpnb_jobs',['feed_item_id'=>$item2,'type'=>'draft','status'=>'queued','attempts'=>0,'created_at'=>$now,'updated_at'=>$now]);$insert($wpdb->prefix.'wpnb_ai_generations',['feed_item_id'=>$item2,'provider'=>'fixture','model'=>'fixture','output_json'=>'{}','input_tokens'=>0,'output_tokens'=>0,'estimated_cost'=>0,'created_at'=>$now]);$insert($wpdb->prefix.'wpnb_daily_usage',['usage_date'=>gmdate('Y-m-d'),'ai_requests'=>1,'input_tokens'=>0,'output_tokens'=>0,'estimated_cost'=>0]);$insert($wpdb->prefix.'wpnb_logs',['level'=>'info','event'=>'upgrade_fixture','message'=>'Fixture log','context_json'=>'{}','created_at'=>$now]);
$post=wp_insert_post(['post_title'=>'Upgrade fixture draft','post_content'=>'Fixture','post_status'=>'draft','post_type'=>'post'],true);if(is_wp_error($post))throw new RuntimeException('draft seed failed');update_post_meta($post,'_wpnb_feed_item_id',$item1);update_option('wpnb_upgrade_fixture',['post_id'=>(int)$post,'item_ids'=>[$item1,$item2]],false);if(class_exists('WordPressNewsBot\\SecretStorage'))(new WordPressNewsBot\SecretStorage())->store('fixture-api-key');echo json_encode(['post_id'=>(int)$post,'items'=>2])."\n";
