<?php
add_filter('wpnb_openai_endpoint',static fn():string=>get_option('wpnb_test_invalid_ai',0)?'https://example.org/v1/invalid-responses':'https://example.org/v1/responses');

add_action('rest_api_init',static function():void{
    $permission=static fn(WP_REST_Request$request):bool=>hash_equals('1',(string)$request->get_header('x-wpnb-test'));
    register_rest_route('wpnb-test/v1','/state',['methods'=>'GET','permission_callback'=>$permission,'callback'=>static function():array{
        global$wpdb;$prefix=$wpdb->prefix.'wpnb_';$engines=[];foreach(['sources','feed_items','jobs','ai_generations','logs','daily_usage','migration_journal']as$table){$status=$wpdb->get_row($wpdb->prepare('SHOW TABLE STATUS LIKE %s',$prefix.$table),ARRAY_A);$engines[$table]=strtolower((string)($status['Engine']??''));}
        $drafts=get_posts(['post_type'=>'post','post_status'=>'draft','numberposts'=>-1,'fields'=>'ids']);$draftRecords=[];foreach($drafts as$id){$feedId=(int)get_post_meta($id,'_wpnb_feed_item_id',true);$sourceItem=$wpdb->get_row($wpdb->prepare("SELECT title,excerpt FROM {$prefix}feed_items WHERE id=%d",$feedId),ARRAY_A);$thumbnailId=(int)get_post_thumbnail_id($id);$draftRecords[]=['id'=>(int)$id,'title'=>(string)get_the_title($id),'content'=>(string)get_post_field('post_content',$id),'status'=>(string)get_post_status($id),'source_title'=>(string)($sourceItem['title']??''),'source_excerpt'=>(string)($sourceItem['excerpt']??''),'source_id'=>(int)get_post_meta($id,'_wpnb_source_id',true),'source_url'=>(string)get_post_meta($id,'_wpnb_source_url',true),'feed_item_id'=>$feedId,'content_hash'=>(string)get_post_meta($id,'_wpnb_content_hash',true),'ai_provider'=>(string)get_post_meta($id,'_wpnb_ai_provider',true),'ai_model'=>(string)get_post_meta($id,'_wpnb_ai_model',true),'generated_at'=>(string)get_post_meta($id,'_wpnb_generated_at',true),'thumbnail_id'=>$thumbnailId,'thumbnail_mime'=>$thumbnailId?(string)get_post_mime_type($thumbnailId):'','thumbnail_alt'=>$thumbnailId?(string)get_post_meta($thumbnailId,'_wp_attachment_image_alt',true):'','thumbnail_caption'=>$thumbnailId?(string)get_post_field('post_excerpt',$thumbnailId):'','thumbnail_content'=>$thumbnailId?(string)get_post_field('post_content',$thumbnailId):''];}
        $attachments=get_posts(['post_type'=>'attachment','post_status'=>'inherit','numberposts'=>-1,'fields'=>'ids','meta_key'=>'_wpnb_image_file_hash']);$media=[];foreach($attachments as$id){$file=(string)get_attached_file($id);$dimensions=$file!==''&&is_file($file)?@getimagesize($file):false;$media[]=['id'=>(int)$id,'mime'=>(string)get_post_mime_type($id),'exists'=>$file!==''&&is_file($file),'real_image'=>is_array($dimensions),'hash'=>(string)get_post_meta($id,'_wpnb_image_file_hash',true),'source_url_protected'=>(string)get_post_meta($id,'_wpnb_source_image_url',true)];}
        return['engines'=>$engines,'sources'=>(int)$wpdb->get_var("SELECT COUNT(*) FROM {$prefix}sources"),'feed_items'=>(int)$wpdb->get_var("SELECT COUNT(*) FROM {$prefix}feed_items"),'items_by_source'=>$wpdb->get_results("SELECT source_name,COUNT(*) total FROM {$prefix}feed_items GROUP BY source_name",ARRAY_A),'image_sources'=>$wpdb->get_results("SELECT image_source,COUNT(*) total FROM {$prefix}feed_items WHERE image_source<>'' GROUP BY image_source",ARRAY_A),'image_statuses'=>$wpdb->get_results("SELECT image_status,COUNT(*) total FROM {$prefix}feed_items GROUP BY image_status",ARRAY_A),'media'=>$media,'drafts'=>count($drafts),'draft_records'=>$draftRecords,'draft_statuses'=>array_values(array_map(static fn(int$id):string=>(string)get_post_status($id),$drafts)),'draft_feed_ids'=>array_values(array_map(static fn(int$id):int=>(int)get_post_meta($id,'_wpnb_feed_item_id',true),$drafts)),'category_links'=>(int)$wpdb->get_var("SELECT COUNT(*) FROM {$prefix}feed_items WHERE wordpress_category_id>0"),'cron_disabled'=>defined('DISABLE_WP_CRON')&&DISABLE_WP_CRON];
    }]);
    register_rest_route('wpnb-test/v1','/invalid-ai',['methods'=>'POST','permission_callback'=>$permission,'callback'=>static function(WP_REST_Request$request):array{$enabled=(bool)$request->get_param('enabled');update_option('wpnb_test_invalid_ai',$enabled?1:0,false);return['enabled'=>$enabled];}]);
    register_rest_route('wpnb-test/v1','/image-settings',['methods'=>'POST','permission_callback'=>$permission,'callback'=>static function():array{$settings=(array)get_option('wpnb_settings',[]);$settings['image_min_width']=1;$settings['image_min_height']=1;$settings['image_max_bytes']=5242880;update_option('wpnb_settings',$settings,false);return['saved'=>true];}]);
    register_rest_route('wpnb-test/v1','/image-test',['methods'=>'POST','permission_callback'=>$permission,'callback'=>static function(WP_REST_Request$request):array{
        global$wpdb;$prefix=$wpdb->prefix.'wpnb_';$kind=sanitize_key((string)$request->get_param('kind'));$urls=['broken'=>'https://example.com/images/broken.jpg','oversized'=>'https://example.com/images/large.png','fake_mime'=>'https://example.com/images/fake.jpg','redirect'=>'https://example.com/images/redirect.png','private_redirect'=>'https://example.com/images/private-redirect.png','private_ip'=>'https://127.0.0.1/image.png'];if(!isset($urls[$kind]))return['status'=>'error','error_code'=>'invalid_test'];$sourceId=(int)$wpdb->get_var("SELECT id FROM {$prefix}sources ORDER BY id ASC LIMIT 1");$now=current_time('mysql',true);$guid='image-test-'.$kind.'-'.wp_generate_uuid4();$record=['source_id'=>$sourceId,'source_name'=>'Image safety fixture','source_feed_url'=>'https://example.com/news-atom.xml','guid'=>$guid,'source_url'=>'https://example.com/items/'.$guid,'normalized_url'=>'https://example.com/items/'.$guid,'title'=>'Image safety '.$kind,'excerpt'=>'Image safety fixture','source_category'=>'Test','wordpress_category_id'=>1,'content_hash'=>hash('sha256',$guid),'image_url'=>$urls[$kind],'image_source'=>'e2e','image_status'=>'missing','image_attachment_id'=>0,'image_hash'=>'','image_error_code'=>'','published_at'=>$now,'status'=>'new','raw_data'=>null,'created_at'=>$now,'updated_at'=>$now];$wpdb->insert($prefix.'feed_items',$record);$itemId=(int)$wpdb->insert_id;$settings=(array)get_option('wpnb_settings',[]);$settings['image_max_bytes']=$kind==='oversized'?65536:5242880;$settings['image_min_width']=1;$settings['image_min_height']=1;update_option('wpnb_settings',$settings,false);$result=(new \WordPressNewsBot\ImageImportService())->import($itemId);$result['item_id']=$itemId;return$result;
    }]);
});
