<?php
declare(strict_types=1);
namespace WordPressNewsBot;

final class Admin
{
    public function register(): void
    {
        add_action('admin_menu',[$this,'menu']); add_action('admin_init',[$this,'settings']);
        foreach(['save_source'=>'saveSource','create_draft'=>'createDraft','bulk_create_drafts'=>'bulkCreateDrafts','save_test_openai'=>'saveAndTestOpenAi','retest_openai'=>'retestOpenAi','delete_openai'=>'deleteOpenAi','skip_setup'=>'skipSetup','finish_setup'=>'finishSetup','manual_run'=>'manualRun'] as $action=>$method) add_action('admin_post_wpnb_'.$action,[$this,$method]);
    }
    public function menu(): void
    {
        add_menu_page(__('WordPress News Bot','wordpress-news-bot'),__('WordPress News Bot','wordpress-news-bot'),'edit_posts','wpnb-dashboard',[$this,'dashboard'],'dashicons-rss',26);
        $items=[[__('Overview','wordpress-news-bot'),'wpnb-dashboard','dashboard'],[__('Setup Wizard','wordpress-news-bot'),'wpnb-setup','setupWizard'],[__('News Sources','wordpress-news-bot'),'wpnb-sources','sources'],[__('News Pool','wordpress-news-bot'),'wpnb-pool','pool'],[__('Settings','wordpress-news-bot'),'wpnb-settings','settingsPage'],[__('System Health','wordpress-news-bot'),'wpnb-health','health']];
        foreach($items as [$title,$slug,$method]) add_submenu_page('wpnb-dashboard',$title,$title,$slug==='wpnb-setup'||$slug==='wpnb-settings'?'manage_options':'edit_posts',$slug,[$this,$method]);
    }
    public function settings(): void
    {
        register_setting('wpnb_settings_group','wpnb_settings',['sanitize_callback'=>static function($v):array{$v=is_array($v)?$v:[];return ['ai_provider'=>'openai','ai_model'=>sanitize_text_field($v['ai_model']??'gpt-4o-mini'),'language'=>sanitize_key($v['language']??'tr'),'tone'=>sanitize_key($v['tone']??'professional'),'min_words'=>min(2000,max(100,absint($v['min_words']??300))),'max_words'=>min(3000,max(200,absint($v['max_words']??700))),'show_attribution'=>empty($v['show_attribution'])?0:1,'daily_ai_quota'=>min(1000,max(0,absint($v['daily_ai_quota']??25))),'max_run_items'=>min(50,max(1,absint($v['max_run_items']??5))),'cron_enabled'=>empty($v['cron_enabled'])?0:1,'retention_days'=>max(1,absint($v['retention_days']??90))];}]);
    }
    private function begin(string $title):void { echo '<div class="wrap wpnb-wrap"><h1>'.esc_html($title).'</h1><style>.wpnb-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(250px,1fr));gap:16px;margin:16px 0}.wpnb-card{background:#fff;border:1px solid #dcdcde;border-radius:8px;padding:18px}.wpnb-card h2{margin-top:0}.wpnb-status{font-weight:600}.wpnb-actions{display:flex;gap:8px;flex-wrap:wrap}.wpnb-danger{color:#b32d2e}</style>'; }
    private function end():void { echo '</div>'; }
    private function settingsValue():array { return (array)get_option('wpnb_settings',[]); }
    private function status():array { return (array)get_option('wpnb_connection_status',['connected'=>0]); }
    private function connected():bool { if(defined('WPNB_OPENAI_API_KEY')&&trim((string)WPNB_OPENAI_API_KEY)!=='')return true; try{return (new SecretStorage())->hasStoredSecret()&&Credentials::openAiKey()!=='';}catch(\Throwable){return false;} }
    private function notice():void { $code=sanitize_key($_GET['wpnb_notice']??''); if(!$code)return; $messages=['saved'=>__('API key was securely saved and the connection test succeeded.','wordpress-news-bot'),'tested'=>__('OpenAI connection test succeeded.','wordpress-news-bot'),'deleted'=>__('Stored API key was deleted.','wordpress-news-bot'),'error'=>__('The operation could not be completed. Check the API key and try again.','wordpress-news-bot'),'decrypt'=>__('The saved API key could not be decrypted. Please enter the key again.','wordpress-news-bot')]; if(isset($messages[$code]))echo '<div class="notice '.($code==='error'||$code==='decrypt'?'notice-error':'notice-success').' is-dismissible"><p>'.esc_html($messages[$code]).'</p></div>'; }
    public function dashboard():void
    {
        global $wpdb; $this->begin(__('WordPress News Bot','wordpress-news-bot')); $this->notice(); $state=(array)get_option('wpnb_setup_state',[]); if(SetupState::needsSetup($state)) echo '<div class="notice notice-warning"><p>'.esc_html__('Setup is not complete.','wordpress-news-bot').' <a class="button button-primary" href="'.esc_url(admin_url('admin.php?page=wpnb-setup')).'">'.esc_html__('Complete Setup','wordpress-news-bot').'</a></p></div>';
        $settings=$this->settingsValue(); $used=(int)$wpdb->get_var($wpdb->prepare('SELECT COALESCE(ai_requests,0) FROM '.Support::table('daily_usage').' WHERE usage_date=%s',gmdate('Y-m-d'))); $quota=(int)($settings['daily_ai_quota']??25); $lastError=(string)$wpdb->get_var("SELECT message FROM ".Support::table('logs')." WHERE level='error' ORDER BY id DESC LIMIT 1"); $cards=[[__('OpenAI','wordpress-news-bot'),$this->connected()?__('Connected','wordpress-news-bot'):__('Not connected','wordpress-news-bot')],[__('RSS sources','wordpress-news-bot'),(string)(int)$wpdb->get_var('SELECT COUNT(*) FROM '.Support::table('sources').' WHERE active=1')],[__('News pool','wordpress-news-bot'),(string)(int)$wpdb->get_var("SELECT COUNT(*) FROM ".Support::table('feed_items')." WHERE status IN ('new','review')")],[__('Drafts','wordpress-news-bot'),(string)(int)$wpdb->get_var("SELECT COUNT(*) FROM ".Support::table('feed_items')." WHERE status='draft_created'")],[__('Daily quota','wordpress-news-bot'),$used.'/'.max(0,$quota-$used)],[__('Automation','wordpress-news-bot'),!empty($settings['cron_enabled'])?__('Enabled','wordpress-news-bot'):__('Disabled','wordpress-news-bot')],[__('Last error','wordpress-news-bot'),$lastError!==''?$lastError:__('None','wordpress-news-bot')],[__('System status','wordpress-news-bot'),(new SecretStorage())->isSupported()?__('Ready','wordpress-news-bot'):__('Encryption unavailable','wordpress-news-bot')]];
        echo '<div class="wpnb-grid">';foreach($cards as[$label,$value])echo '<div class="wpnb-card"><h2>'.esc_html($label).'</h2><div class="wpnb-status">'.esc_html($value).'</div></div>';echo '</div>'; $this->end();
    }
    public function setupWizard():void
    {
        $this->requireManage(); $step=min(5,max(1,absint($_GET['step']??1))); $titles=[1=>__('OpenAI connection','wordpress-news-bot'),2=>__('Content generation','wordpress-news-bot'),3=>__('Usage limits','wordpress-news-bot'),4=>__('First RSS source','wordpress-news-bot'),5=>__('Setup summary','wordpress-news-bot')]; $this->begin(__('Setup Wizard','wordpress-news-bot')); $this->notice(); echo '<p>'.esc_html(sprintf(__('Step %1$d of 5: %2$s','wordpress-news-bot'),$step,$titles[$step])).'</p><div class="wpnb-card">';
        if($step===1){$this->connectionCard(true);}elseif($step===2){$this->settingsForm('content');}elseif($step===3){$this->settingsForm('limits');}elseif($step===4){$this->sourceForm(true);}else{echo '<p>'.esc_html__('Your settings can be changed at any time. Generated posts always remain drafts.','wordpress-news-bot').'</p><form method="post" action="'.esc_url(admin_url('admin-post.php')).'">';wp_nonce_field('wpnb_finish_setup');echo '<input type="hidden" name="action" value="wpnb_finish_setup">';submit_button(__('Finish Setup','wordpress-news-bot'),'primary','submit',false);echo '</form>';}
        echo '</div><div class="wpnb-actions">';if($step<5)echo '<a class="button button-primary" href="'.esc_url(admin_url('admin.php?page=wpnb-setup&step='.($step+1))).'">'.esc_html__('Next','wordpress-news-bot').'</a>';echo '<form method="post" action="'.esc_url(admin_url('admin-post.php')).'">';wp_nonce_field('wpnb_skip_setup');echo '<input type="hidden" name="action" value="wpnb_skip_setup"><button class="button">'.esc_html__('Skip setup','wordpress-news-bot').'</button></form></div>'; $this->end();
    }
    public function settingsPage():void
    {
        $this->requireManage();$this->begin(__('Settings','wordpress-news-bot'));$this->notice();echo '<div class="wpnb-grid"><div class="wpnb-card">';$this->connectionCard(false);echo '</div><div class="wpnb-card"><h2>'.esc_html__('Content Generation','wordpress-news-bot').'</h2>';$this->settingsForm('content');echo '</div><div class="wpnb-card"><h2>'.esc_html__('Usage Limits','wordpress-news-bot').'</h2>';$this->settingsForm('limits');echo '</div><div class="wpnb-card"><h2>'.esc_html__('Automation','wordpress-news-bot').'</h2>';$this->automationCard();echo '</div></div>';$this->end();
    }
    private function connectionCard(bool $wizard):void
    {
        $s=$this->settingsValue();$status=$this->status();$connected=$this->connected();echo '<h2>'.esc_html__('OpenAI Connection','wordpress-news-bot').'</h2><p class="wpnb-status">'.esc_html($connected?__('Connected','wordpress-news-bot'):__('Not connected','wordpress-news-bot')).'</p>';
        if($connected)echo '<p>'.esc_html__('API key securely saved.','wordpress-news-bot').'</p>';if(!empty($status['tested_at']))echo '<p>'.esc_html(sprintf(__('Last successful test: %s','wordpress-news-bot'),$status['tested_at'])).'<br>'.esc_html(sprintf(__('Tested model: %s','wordpress-news-bot'),$status['model']??'')).'<br>'.esc_html(sprintf(__('Response time: %d ms','wordpress-news-bot'),(int)($status['duration_ms']??0))).'<br>'.esc_html(sprintf(__('Request ID: %s','wordpress-news-bot'),$status['request_id']??'')).'</p>';
        echo '<form method="post" action="'.esc_url(admin_url('admin-post.php')).'">';wp_nonce_field('wpnb_save_test_openai');echo '<input type="hidden" name="action" value="wpnb_save_test_openai"><input type="hidden" name="return_page" value="'.esc_attr($wizard?'wpnb-setup':'wpnb-settings').'"><p><label for="wpnb-api-key">'.esc_html__('OpenAI API key','wordpress-news-bot').'</label><br><input id="wpnb-api-key" class="regular-text" type="password" name="api_key" value="" autocomplete="new-password" spellcheck="false" required></p><p><label for="wpnb-model">'.esc_html__('Model','wordpress-news-bot').'</label><br><input id="wpnb-model" class="regular-text" name="model" value="'.esc_attr($s['ai_model']??'gpt-4o-mini').'" required></p><button class="button button-primary">'.esc_html($connected?__('Change API Key and Test','wordpress-news-bot'):__('Save and Test Connection','wordpress-news-bot')).'</button></form>';
        if($connected){echo '<div class="wpnb-actions" style="margin-top:12px"><form method="post" action="'.esc_url(admin_url('admin-post.php')).'">';wp_nonce_field('wpnb_retest_openai');echo '<input type="hidden" name="action" value="wpnb_retest_openai"><button class="button">'.esc_html__('Retest Connection','wordpress-news-bot').'</button></form><form method="post" action="'.esc_url(admin_url('admin-post.php')).'" onsubmit="return confirm(&quot;'.esc_attr(__('Delete the stored API key?','wordpress-news-bot')).'&quot;)">';wp_nonce_field('wpnb_delete_openai');echo '<input type="hidden" name="action" value="wpnb_delete_openai"><button class="button wpnb-danger">'.esc_html__('Delete API Key','wordpress-news-bot').'</button></form></div>';}
    }
    private function settingsForm(string $section):void
    {
        $s=$this->settingsValue();echo '<form method="post" action="options.php">';settings_fields('wpnb_settings_group');foreach($s as$key=>$value)if(!in_array($key,$section==='content'?['language','tone','min_words','max_words','show_attribution']:['daily_ai_quota','max_run_items'],true))echo '<input type="hidden" name="wpnb_settings['.esc_attr($key).']" value="'.esc_attr((string)$value).'">';
        if($section==='content')echo '<p>'.esc_html__('Language','wordpress-news-bot').'<br><select name="wpnb_settings[language]"><option value="tr">'.esc_html__('Turkish','wordpress-news-bot').'</option></select></p><p>'.esc_html__('Tone','wordpress-news-bot').'<br><select name="wpnb_settings[tone]"><option value="professional">'.esc_html__('Professional','wordpress-news-bot').'</option><option value="neutral">'.esc_html__('Neutral','wordpress-news-bot').'</option></select></p><p>'.esc_html__('Minimum words','wordpress-news-bot').'<br><input type="number" name="wpnb_settings[min_words]" value="'.esc_attr((string)($s['min_words']??300)).'"></p><p>'.esc_html__('Maximum words','wordpress-news-bot').'<br><input type="number" name="wpnb_settings[max_words]" value="'.esc_attr((string)($s['max_words']??700)).'"></p><label><input type="checkbox" name="wpnb_settings[show_attribution]" value="1" '.checked((int)($s['show_attribution']??1),1,false).'> '.esc_html__('Show source attribution','wordpress-news-bot').'</label><p><strong>'.esc_html__('Post status: Draft','wordpress-news-bot').'</strong></p>';
        else echo '<p>'.esc_html__('Daily maximum AI news','wordpress-news-bot').'<br><input type="number" name="wpnb_settings[daily_ai_quota]" value="'.esc_attr((string)($s['daily_ai_quota']??25)).'"></p><p>'.esc_html__('Maximum news per run','wordpress-news-bot').'<br><input type="number" name="wpnb_settings[max_run_items]" value="'.esc_attr((string)($s['max_run_items']??5)).'"></p>';
        submit_button(__('Save Settings','wordpress-news-bot'),'secondary','submit',false);echo '</form>';
    }
    private function automationCard():void { $s=$this->settingsValue();if(defined('DISABLE_WP_CRON')&&DISABLE_WP_CRON){echo '<p>'.esc_html__('Automatic operations are currently unavailable. Manual news creation will continue to work.','wordpress-news-bot').'</p>';return;} $next=wp_next_scheduled('wpnb_poll_sources');echo '<p>'.esc_html(!empty($s['cron_enabled'])?__('Automation is enabled.','wordpress-news-bot'):__('Automation is disabled.','wordpress-news-bot')).'</p><p>'.esc_html(sprintf(__('Last run: %s','wordpress-news-bot'),get_option('wpnb_last_automation_run',__('Never','wordpress-news-bot')))).'<br>'.esc_html(sprintf(__('Next run: %s','wordpress-news-bot'),$next?wp_date('Y-m-d H:i:s',$next):__('Not scheduled','wordpress-news-bot'))).'</p><form method="post" action="options.php">';settings_fields('wpnb_settings_group');foreach($s as$key=>$value)if($key!=='cron_enabled')echo '<input type="hidden" name="wpnb_settings['.esc_attr($key).']" value="'.esc_attr((string)$value).'">';echo '<label><input type="checkbox" name="wpnb_settings[cron_enabled]" value="1" '.checked((int)($s['cron_enabled']??0),1,false).'> '.esc_html__('Enable automation','wordpress-news-bot').'</label><p>';submit_button(__('Save Automation','wordpress-news-bot'),'secondary','submit',false);echo '</p></form><form method="post" action="'.esc_url(admin_url('admin-post.php')).'">';wp_nonce_field('wpnb_manual_run');echo '<input type="hidden" name="action" value="wpnb_manual_run"><button class="button">'.esc_html__('Run Manually','wordpress-news-bot').'</button></form>'; }
    public function sources():void { global $wpdb;$rows=$wpdb->get_results('SELECT * FROM '.Support::table('sources').' ORDER BY id DESC');$this->begin(__('News Sources','wordpress-news-bot'));echo '<table class="widefat"><thead><tr><th>'.esc_html__('Name','wordpress-news-bot').'</th><th>URL</th><th>'.esc_html__('Status','wordpress-news-bot').'</th></tr></thead><tbody>';foreach($rows as$row)echo '<tr><td>'.esc_html($row->name).'</td><td>'.esc_html($row->feed_url).'</td><td>'.esc_html($row->active?__('Active','wordpress-news-bot'):__('Inactive','wordpress-news-bot')).'</td></tr>';echo '</tbody></table><h2>'.esc_html__('Add source','wordpress-news-bot').'</h2>';$this->sourceForm(false);$this->end(); }
    private function sourceForm(bool$wizard):void { echo '<form method="post" action="'.esc_url(admin_url('admin-post.php')).'">';wp_nonce_field('wpnb_save_source');echo '<input type="hidden" name="action" value="wpnb_save_source"><input type="hidden" name="return_page" value="'.esc_attr($wizard?'wpnb-setup':'wpnb-sources').'"><p><input required name="name" placeholder="'.esc_attr__('Source name','wordpress-news-bot').'" class="regular-text"></p><p><input required type="url" name="feed_url" placeholder="https://example.com/feed" class="regular-text"></p><p><input name="allowed_domains" placeholder="example.com" class="regular-text"></p>';submit_button(__('Save Source','wordpress-news-bot'));echo '</form>'; }
    public function saveSource():void { $this->requireAction('wpnb_save_source');global$wpdb;$url=esc_url_raw(wp_unslash($_POST['feed_url']??''));$host=(string)(wp_parse_url($url)['host']??'');$domains=array_filter(array_map('sanitize_text_field',preg_split('/[\r\n,]+/',(string)wp_unslash($_POST['allowed_domains']??''))?:[]));if(!$domains&&$host)$domains=[$host];if(!Security::validateFeedUrl($url,$domains))wp_die(esc_html__('The source URL did not pass security validation.','wordpress-news-bot'));$now=Support::now();$wpdb->insert(Support::table('sources'),['name'=>sanitize_text_field(wp_unslash($_POST['name']??'')),'feed_url'=>$url,'allowed_domains'=>implode("\n",$domains),'created_at'=>$now,'updated_at'=>$now]);$return=sanitize_key($_POST['return_page']??'wpnb-sources');$this->redirect($return==='wpnb-setup'?'wpnb-setup&step=5':'wpnb-sources'); }
    public function pool():void { global$wpdb;$rows=$wpdb->get_results('SELECT id,title,source_url,status FROM '.Support::table('feed_items').' ORDER BY id DESC LIMIT 100');$this->begin(__('News Pool','wordpress-news-bot'));echo '<table class="widefat"><thead><tr><th>'.esc_html__('Title','wordpress-news-bot').'</th><th>'.esc_html__('Status','wordpress-news-bot').'</th></tr></thead><tbody>';foreach($rows as$row)echo '<tr><td>'.esc_html($row->title).'</td><td>'.esc_html($row->status).'</td></tr>';echo '</tbody></table>';$this->end(); }
    public function health():void { $this->begin(__('System Health','wordpress-news-bot'));echo '<p>'.esc_html((new SecretStorage())->isSupported()?__('Secure encryption is available.','wordpress-news-bot'):__('Secure encryption is unavailable. API keys cannot be stored.','wordpress-news-bot')).'</p>';$this->automationCard();$this->end(); }
    public function saveAndTestOpenAi():void { $this->requireAction('wpnb_save_test_openai');$key=trim((string)wp_unslash($_POST['api_key']??''));$model=sanitize_text_field(wp_unslash($_POST['model']??'gpt-4o-mini'));$return=sanitize_key($_POST['return_page']??'wpnb-settings');if(!in_array($return,['wpnb-settings','wpnb-setup'],true))$return='wpnb-settings';try{$result=(new ConnectionService(new SecretStorage()))->saveAndTest($key,$model);$s=$this->settingsValue();$s['ai_model']=$model;$s['ai_provider']='openai';update_option('wpnb_settings',$s,false);$this->saveStatus($result);$this->redirect($return,'saved');}catch(\Throwable){$this->redirect($return,'error');} }
    public function retestOpenAi():void { $this->requireAction('wpnb_retest_openai');try{$result=(new ConnectionService(new SecretStorage()))->retest((string)($this->settingsValue()['ai_model']??'gpt-4o-mini'));$this->saveStatus($result);$this->redirect('wpnb-settings','tested');}catch(\Throwable$e){$this->redirect('wpnb-settings',str_contains($e->getMessage(),'şifresi')?'decrypt':'error');} }
    public function deleteOpenAi():void { $this->requireAction('wpnb_delete_openai');(new ConnectionService(new SecretStorage()))->delete();update_option('wpnb_connection_status',['connected'=>0],false);$this->redirect('wpnb-settings','deleted'); }
    private function saveStatus(array$result):void { update_option('wpnb_connection_status',['connected'=>1,'tested_at'=>current_time('mysql'),'model'=>sanitize_text_field($result['model']),'duration_ms'=>(int)$result['duration_ms'],'request_id'=>sanitize_text_field($result['request_id']),'http_class'=>(int)$result['http_class']],false); }
    public function skipSetup():void { $this->requireAction('wpnb_skip_setup');update_option('wpnb_setup_state',SetupState::skipped(),false);$this->redirect('wpnb-dashboard'); }
    public function finishSetup():void { $this->requireAction('wpnb_finish_setup');update_option('wpnb_setup_state',SetupState::completed(),false);$this->redirect('wpnb-dashboard'); }
    public function manualRun():void { $this->requireAction('wpnb_manual_run');do_action('wpnb_sources_polled');update_option('wpnb_last_automation_run',Support::now(),false);$this->redirect('wpnb-settings'); }
    public function createDraft():void { $id=absint($_POST['item_id']??0);if(!Security::canReview()||!check_admin_referer('wpnb_create_draft_'.$id))wp_die(esc_html__('Invalid request.','wordpress-news-bot'));(new DraftService())->create($id);$this->redirect('wpnb-pool'); }
    public function bulkCreateDrafts():void { $this->requireAction('wpnb_bulk_create_drafts');foreach(array_slice(array_map('absint',(array)($_POST['item_ids']??[])),0,5)as$id)try{(new DraftService())->create($id);}catch(\Throwable){}$this->redirect('wpnb-pool'); }
    private function requireManage():void { if(!Security::canManage())wp_die(esc_html__('You do not have permission to access this page.','wordpress-news-bot')); }
    private function requireAction(string$nonce):void { $this->requireManage();if(!check_admin_referer($nonce))wp_die(esc_html__('Invalid security token.','wordpress-news-bot')); }
    private function redirect(string$page,string$notice=''):never { $url=admin_url('admin.php?page='.$page.($notice?'&wpnb_notice='.$notice:''));wp_safe_redirect($url);exit; }
}
