<?php
declare(strict_types=1);
namespace WordPressNewsBot;

final class Admin
{
    public function register(): void
    {
        add_action('admin_menu',[$this,'menu']); add_action('admin_init',[$this,'settings']);
        foreach(['save_source'=>'saveSource','test_source'=>'testSource','toggle_source'=>'toggleSource','delete_source'=>'deleteSource','bulk_sources'=>'bulkSources','dismiss_recovery'=>'dismissRecovery','repair_database'=>'repairDatabase','create_draft'=>'createDraft','bulk_create_drafts'=>'bulkCreateDrafts','save_test_openai'=>'saveAndTestOpenAi','retest_openai'=>'retestOpenAi','delete_openai'=>'deleteOpenAi','skip_setup'=>'skipSetup','finish_setup'=>'finishSetup','manual_run'=>'manualRun'] as $action=>$method) add_action('admin_post_wpnb_'.$action,[$this,$method]);
    }
    public function menu(): void
    {
        add_menu_page(__('WordPress News Bot','wordpress-news-bot'),__('WordPress News Bot','wordpress-news-bot'),'edit_posts','wpnb-dashboard',[$this,'dashboard'],'dashicons-rss',26);
        $items=[[__('Overview','wordpress-news-bot'),'wpnb-dashboard','dashboard'],[__('Setup Wizard','wordpress-news-bot'),'wpnb-setup','setupWizard'],[__('News Sources','wordpress-news-bot'),'wpnb-sources','sources'],[__('News Pool','wordpress-news-bot'),'wpnb-pool','pool'],[__('Settings','wordpress-news-bot'),'wpnb-settings','settingsPage'],[__('System Health','wordpress-news-bot'),'wpnb-health','health']];
        foreach($items as [$title,$slug,$method]) add_submenu_page('wpnb-dashboard',$title,$title,in_array($slug,['wpnb-setup','wpnb-sources','wpnb-settings','wpnb-health'],true)?'manage_options':'edit_posts',$slug,[$this,$method]);
    }
    public function settings(): void
    {
        register_setting('wpnb_settings_group','wpnb_settings',['sanitize_callback'=>static function($v):array{$v=is_array($v)?$v:[];return ['ai_provider'=>'openai','ai_model'=>sanitize_text_field($v['ai_model']??'gpt-4o-mini'),'language'=>sanitize_key($v['language']??'tr'),'tone'=>sanitize_key($v['tone']??'professional'),'min_words'=>min(2000,max(100,absint($v['min_words']??300))),'max_words'=>min(3000,max(200,absint($v['max_words']??700))),'show_attribution'=>empty($v['show_attribution'])?0:1,'daily_ai_quota'=>min(1000,max(0,absint($v['daily_ai_quota']??25))),'max_run_items'=>min(50,max(1,absint($v['max_run_items']??5))),'cron_enabled'=>empty($v['cron_enabled'])?0:1,'retention_days'=>max(1,absint($v['retention_days']??90))];}]);
    }
    private function begin(string $title):void { echo '<div class="wrap wpnb-wrap"><h1>'.esc_html($title).'</h1><style>.wpnb-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(250px,1fr));gap:16px;margin:16px 0}.wpnb-card{background:#fff;border:1px solid #dcdcde;border-radius:8px;padding:18px}.wpnb-card h2{margin-top:0}.wpnb-status{font-weight:600}.wpnb-actions{display:flex;gap:8px;flex-wrap:wrap;align-items:center}.wpnb-danger{color:#b32d2e}.wpnb-source-actions{display:flex;gap:6px;flex-wrap:wrap}.wpnb-source-actions form{margin:0}.wpnb-field{margin:0 0 16px}.wpnb-field label{display:block;font-weight:600;margin-bottom:5px}.wpnb-field .description{max-width:620px}.wpnb-source-url{overflow-wrap:anywhere;max-width:320px}@media(max-width:782px){.wpnb-sources-table thead{display:none}.wpnb-sources-table tr{display:block;padding:12px}.wpnb-sources-table td{display:block;border:0;padding:6px 10px}.wpnb-sources-table td:before{content:attr(data-label);display:block;font-weight:600}.wpnb-source-actions .button{min-height:40px}}</style>'; }
    private function end():void { echo '</div>'; }
    private function settingsValue():array { return (array)get_option('wpnb_settings',[]); }
    private function status():array { return (array)get_option('wpnb_connection_status',['connected'=>0]); }
    private function connected():bool { if(defined('WPNB_OPENAI_API_KEY')&&trim((string)WPNB_OPENAI_API_KEY)!=='')return true; try{return (new SecretStorage())->hasStoredSecret()&&Credentials::openAiKey()!=='';}catch(\Throwable){return false;} }
    private function notice():void
    {
        $code=sanitize_key($_GET['wpnb_notice']??'');if(!$code)return;
        $messages=['saved'=>__('API key was securely saved and the connection test succeeded.','wordpress-news-bot'),'tested'=>__('OpenAI connection test succeeded.','wordpress-news-bot'),'deleted'=>__('Stored API key was deleted.','wordpress-news-bot'),'error'=>__('The operation could not be completed. Check the API key and try again.','wordpress-news-bot'),'decrypt'=>__('The saved API key could not be decrypted. Please enter the key again.','wordpress-news-bot'),'source_saved'=>__('The news source was saved and its connection was verified.','wordpress-news-bot'),'source_updated'=>__('The news source was updated.','wordpress-news-bot'),'source_deleted'=>__('The news source and its unprocessed pool records were deleted. Existing WordPress posts were preserved.','wordpress-news-bot'),'source_toggled'=>__('The source status was updated.','wordpress-news-bot'),'source_tested'=>__('The RSS/Atom connection test succeeded.','wordpress-news-bot'),'source_duplicate'=>__('This RSS source is already registered.','wordpress-news-bot'),'source_error'=>__('The source could not be processed. Check the RSS URL and try again.','wordpress-news-bot'),'source_diagnostic_error'=>__('The source test failed.','wordpress-news-bot'),'db_repair_required'=>__('The physical database schema must be repaired before the source can be saved.','wordpress-news-bot'),'db_repaired'=>__('Database repair completed and the physical schema was verified.','wordpress-news-bot'),'db_repair_failed'=>__('Database repair could not be completed safely. No tables or source data were deleted.','wordpress-news-bot'),'bulk_done'=>__('The bulk source operation was completed.','wordpress-news-bot'),'draft_created'=>__('The selected WordPress draft was created.','wordpress-news-bot'),'draft_error'=>__('The draft could not be created. No post was published.','wordpress-news-bot')];
        if(!isset($messages[$code]))return;$detail=$this->takeAdminNotice();$error=in_array($code,['error','decrypt','source_error','source_duplicate','source_diagnostic_error','db_repair_required','db_repair_failed','draft_error'],true);echo '<div class="notice '.($error?'notice-error':'notice-success').' is-dismissible"><p>'.esc_html($messages[$code]);if($detail!==''&&($code==='source_diagnostic_error'||str_starts_with($code,'db_')||!$error))echo '<br>'.esc_html($detail);echo '</p></div>';
    }
    public function dashboard():void
    {
        global $wpdb; $this->begin(__('WordPress News Bot','wordpress-news-bot')); $this->notice(); $state=(array)get_option('wpnb_setup_state',[]); if(SetupState::needsSetup($state)) echo '<div class="notice notice-warning"><p>'.esc_html__('Setup is not complete.','wordpress-news-bot').' <a class="button button-primary" href="'.esc_url(admin_url('admin.php?page=wpnb-setup')).'">'.esc_html__('Complete Setup','wordpress-news-bot').'</a></p></div>';
        $settings=$this->settingsValue(); $used=(int)$wpdb->get_var($wpdb->prepare('SELECT COALESCE(ai_requests,0) FROM '.Support::table('daily_usage').' WHERE usage_date=%s',gmdate('Y-m-d'))); $quota=(int)($settings['daily_ai_quota']??25); $lastError=(string)$wpdb->get_var("SELECT message FROM ".Support::table('logs')." WHERE level='error' ORDER BY id DESC LIMIT 1"); $cards=[[__('OpenAI','wordpress-news-bot'),$this->connected()?__('Connected','wordpress-news-bot'):__('Not connected','wordpress-news-bot')],[__('RSS sources','wordpress-news-bot'),(string)(int)$wpdb->get_var('SELECT COUNT(*) FROM '.Support::table('sources').' WHERE active=1')],[__('News pool','wordpress-news-bot'),(string)(int)$wpdb->get_var("SELECT COUNT(*) FROM ".Support::table('feed_items')." WHERE status IN ('new','review')")],[__('Drafts','wordpress-news-bot'),(string)(int)$wpdb->get_var("SELECT COUNT(*) FROM ".Support::table('feed_items')." WHERE status='draft_created'")],[__('Daily quota','wordpress-news-bot'),$used.'/'.max(0,$quota)],[__('Automation','wordpress-news-bot'),!empty($settings['cron_enabled'])?__('Enabled','wordpress-news-bot'):__('Disabled','wordpress-news-bot')],[__('Last error','wordpress-news-bot'),$lastError!==''?$lastError:__('None','wordpress-news-bot')],[__('System status','wordpress-news-bot'),(new SecretStorage())->isSupported()?__('Ready','wordpress-news-bot'):__('Encryption unavailable','wordpress-news-bot')]];
        echo '<div class="wpnb-grid">';foreach($cards as[$label,$value])echo '<div class="wpnb-card"><h2>'.esc_html($label).'</h2><div class="wpnb-status">'.esc_html($value).'</div></div>';echo '</div>'; $this->end();
    }
    public function setupWizard():void
    {
        $this->requireManage(); $step=min(5,max(1,absint($_GET['step']??1))); $titles=[1=>__('OpenAI connection','wordpress-news-bot'),2=>__('Content generation','wordpress-news-bot'),3=>__('Usage limits','wordpress-news-bot'),4=>__('First RSS source','wordpress-news-bot'),5=>__('Setup summary','wordpress-news-bot')]; $this->begin(__('Setup Wizard','wordpress-news-bot')); $this->notice(); echo '<p>'.esc_html(sprintf(__('Step %1$d of 5: %2$s','wordpress-news-bot'),$step,$titles[$step])).'</p><div class="wpnb-card">';
        if($step===1){$this->connectionCard(true);}elseif($step===2){$this->settingsForm('content');}elseif($step===3){$this->settingsForm('limits');}elseif($step===4){$this->sourceForm(true);}else{echo '<p>'.esc_html__('Your settings can be changed at any time. Generated posts always remain drafts.','wordpress-news-bot').'</p><form method="post" action="'.esc_url(admin_url('admin-post.php')).'">';wp_nonce_field('wpnb_finish_setup');echo '<input type="hidden" name="action" value="wpnb_finish_setup">';submit_button(__('Finish Setup','wordpress-news-bot'),'primary','submit',false);echo '</form>';}
        echo '</div><div class="wpnb-actions">';if($step<5)echo '<a class="button button-primary" href="'.esc_url(admin_url('admin.php?page=wpnb-setup&step='.($step+1))).'">'.esc_html__('Next','wordpress-news-bot').'</a>';echo '<form method="post" action="'.esc_url(admin_url('admin-post.php')).'">';wp_nonce_field('wpnb_skip_setup');echo '<input type="hidden" name="action" value="wpnb_skip_setup"><button class="button">'.esc_html__('Skip setup','wordpress-news-bot').'</button></form></div>'; $this->end();
    }
    public function settingsPage():void
    {
        $this->requireManage();$this->begin(__('Settings','wordpress-news-bot'));$this->notice();echo '<div class="wpnb-grid"><div class="wpnb-card">';$this->connectionCard(false);echo '</div><div class="wpnb-card"><h2>'.esc_html__('Content Generation','wordpress-news-bot').'</h2>';$this->settingsForm('content');echo '</div><div class="wpnb-card"><h2>'.esc_html__('Usage Limits','wordpress-news-bot').'</h2>';$this->settingsForm('limits');echo '</div><div class="wpnb-card"><h2>'.esc_html__('Automation','wordpress-news-bot').'</h2>';$this->automationCard();echo '</div></div>';$this->end();
    }
    private function connectionCard(bool $wizard):void
    {
        $s=$this->settingsValue();$status=$this->status();$connected=$this->connected();echo '<h2>'.esc_html__('OpenAI Connection','wordpress-news-bot').'</h2><p class="wpnb-status">'.esc_html($connected?__('Connected','wordpress-news-bot'):__('Not connected','wordpress-news-bot')).'</p>';
        if($connected)echo '<p>'.esc_html__('API key securely saved.','wordpress-news-bot').'</p>';if(!empty($status['tested_at']))echo '<p>'.esc_html(sprintf(__('Last successful test: %s','wordpress-news-bot'),$status['tested_at'])).'<br>'.esc_html(sprintf(__('Tested model: %s','wordpress-news-bot'),$status['model']??'')).'<br>'.esc_html(sprintf(__('Response time: %d ms','wordpress-news-bot'),(int)($status['duration_ms']??0))).'<br>'.esc_html(sprintf(__('Request ID: %s','wordpress-news-bot'),$status['request_id']??'')).'</p>';
        echo '<form method="post" action="'.esc_url(admin_url('admin-post.php')).'">';wp_nonce_field('wpnb_save_test_openai');echo '<input type="hidden" name="action" value="wpnb_save_test_openai"><input type="hidden" name="return_page" value="'.esc_attr($wizard?'wpnb-setup':'wpnb-settings').'"><p><label for="wpnb-api-key">'.esc_html__('OpenAI API key','wordpress-news-bot').'</label><br><input id="wpnb-api-key" class="regular-text" type="password" name="api_key" value="" autocomplete="new-password" spellcheck="false" required></p><p><label for="wpnb-model">'.esc_html__('Model','wordpress-news-bot').'</label><br><input id="wpnb-model" class="regular-text" name="model" value="'.esc_attr($s['ai_model']??'gpt-4o-mini').'" required></p><button class="button button-primary">'.esc_html($connected?__('Change API Key and Test','wordpress-news-bot'):__('Save and Test Connection','wordpress-news-bot')).'</button></form>';
        if($connected){echo '<div class="wpnb-actions" style="margin-top:12px"><form method="post" action="'.esc_url(admin_url('admin-post.php')).'">';wp_nonce_field('wpnb_retest_openai');echo '<input type="hidden" name="action" value="wpnb_retest_openai"><button class="button">'.esc_html__('Retest Connection','wordpress-news-bot').'</button></form><form method="post" action="'.esc_url(admin_url('admin-post.php')).'" onsubmit="return confirm(&quot;'.esc_attr(__('Delete the stored API key?','wordpress-news-bot')).'&quot;)">';wp_nonce_field('wpnb_delete_openai');echo '<input type="hidden" name="action" value="wpnb_delete_openai"><button class="button wpnb-danger">'.esc_html__('Delete API Key','wordpress-news-bot').'</button></form></div>';}
    }
    private function settingsForm(string $section):void
    {
        $s=$this->settingsValue();echo '<form method="post" action="options.php">';settings_fields('wpnb_settings_group');foreach($s as$key=>$value)if(!in_array($key,$section==='content'?['language','tone','min_words','max_words','show_attribution']:['daily_ai_quota','max_run_items'],true))echo '<input type="hidden" name="wpnb_settings['.esc_attr($key).']" value="'.esc_attr((string)$value).'">';
        if($section==='content')echo '<p>'.esc_html__('Language','wordpress-news-bot').'<br><select name="wpnb_settings[language]"><option value="tr">'.esc_html__('Turkish','wordpress-news-bot').'</option></select></p><p>'.esc_html__('Tone','wordpress-news-bot').'<br><select name="wpnb_settings[tone]"><option value="professional">'.esc_html__('Professional','wordpress-news-bot').'</option><option value="neutral">'.esc_html__('Neutral','wordpress-news-bot').'</option></select></p><p>'.esc_html__('Minimum words','wordpress-news-bot').'<br><input type="number" name="wpnb_settings[min_words]" value="'.esc_attr((string)($s['min_words']??300)).'"></p><p>'.esc_html__('Maximum words','wordpress-news-bot').'<br><input type="number" name="wpnb_settings[max_words]" value="'.esc_attr((string)($s['max_words']??700)).'"></p><label><input type="checkbox" name="wpnb_settings[show_attribution]" value="1" '.checked((int)($s['show_attribution']??1),1,false).'> '.esc_html__('Show source attribution','wordpress-news-bot').'</label><p><strong>'.esc_html__('Post status: Draft','wordpress-news-bot').'</strong></p>';
        else echo '<p>'.esc_html__('Daily maximum AI news','wordpress-news-bot').'<br><input type="number" name="wpnb_settings[daily_ai_quota]" value="'.esc_attr((string)($s['daily_ai_quota']??25)).'"></p><p>'.esc_html__('Maximum news per run','wordpress-news-bot').'<br><input type="number" name="wpnb_settings[max_run_items]" value="'.esc_attr((string)($s['max_run_items']??5)).'"></p>';
        submit_button(__('Save Settings','wordpress-news-bot'),'secondary','submit',false);echo '</form>';
    }
    private function automationCard():void { $s=$this->settingsValue();if(defined('DISABLE_WP_CRON')&&DISABLE_WP_CRON){echo '<p>'.esc_html__('Automatic operations are currently unavailable. Manual news creation will continue to work.','wordpress-news-bot').'</p>';return;} $next=wp_next_scheduled('wpnb_poll_sources');echo '<p>'.esc_html(!empty($s['cron_enabled'])?__('Automation is enabled.','wordpress-news-bot'):__('Automation is disabled.','wordpress-news-bot')).'</p><p>'.esc_html(sprintf(__('Last run: %s','wordpress-news-bot'),get_option('wpnb_last_automation_run',__('Never','wordpress-news-bot')))).'<br>'.esc_html(sprintf(__('Next run: %s','wordpress-news-bot'),$next?wp_date('Y-m-d H:i:s',$next):__('Not scheduled','wordpress-news-bot'))).'</p><form method="post" action="options.php">';settings_fields('wpnb_settings_group');foreach($s as$key=>$value)if($key!=='cron_enabled')echo '<input type="hidden" name="wpnb_settings['.esc_attr($key).']" value="'.esc_attr((string)$value).'">';echo '<label><input type="checkbox" name="wpnb_settings[cron_enabled]" value="1" '.checked((int)($s['cron_enabled']??0),1,false).'> '.esc_html__('Enable automation','wordpress-news-bot').'</label><p>';submit_button(__('Save Automation','wordpress-news-bot'),'secondary','submit',false);echo '</p></form><form method="post" action="'.esc_url(admin_url('admin-post.php')).'">';wp_nonce_field('wpnb_manual_run');echo '<input type="hidden" name="action" value="wpnb_manual_run"><button class="button">'.esc_html__('Run Manually','wordpress-news-bot').'</button></form>'; }
    public function sources():void
    {
        $this->requireManage();
        global $wpdb;
        $sourceHealth=(new DatabaseHealth($wpdb))->sourceReady();$rows=$sourceHealth['ready']?$wpdb->get_results('SELECT * FROM '.Support::table('sources').' ORDER BY id DESC'):[];
        $editId=absint($_GET['wpnb_edit']??0);
        $deleteId=absint($_GET['wpnb_delete_confirm']??0);
        $edit=$sourceHealth['ready']&&$editId?(array)$wpdb->get_row($wpdb->prepare('SELECT * FROM '.Support::table('sources').' WHERE id=%d LIMIT 1',$editId),ARRAY_A):[];
        $formState=(array)get_transient($this->sourceFormKey());if(!$edit&&isset($formState['input'])&&is_array($formState['input']))$edit=$formState['input'];
        $this->begin(__('News Sources','wordpress-news-bot'));
        $this->notice();
        if(!$sourceHealth['ready'])echo '<div class="notice notice-error"><p>'.esc_html__('The source database schema requires repair. The saved connection test will be kept while you repair it.','wordpress-news-bot').' <a href="'.esc_url(admin_url('admin.php?page=wpnb-health')).'">'.esc_html__('Open Database Health','wordpress-news-bot').'</a></p></div>';
        $recovery=(array)get_option('wpnb_source_recovery_required',[]);$recoveryHash=$recovery?hash('sha256',Support::json($recovery)):'';$ack=(string)get_user_meta(get_current_user_id(),'wpnb_source_recovery_ack',true);if($recovery&&$ack!==$recoveryHash){$message=($recovery['reason']??'')==='missing_snapshot'?__('The previous source migration did not complete. Source information could not be restored automatically. Please add the source again.','wordpress-news-bot'):__('The source migration could not be completed. Existing source records were restored from the migration journal. Please review the error log before trying again.','wordpress-news-bot');echo '<div class="notice notice-error"><p>'.esc_html($message).'</p><form method="post" action="'.esc_url(admin_url('admin-post.php')).'">';wp_nonce_field('wpnb_dismiss_recovery');echo '<input type="hidden" name="action" value="wpnb_dismiss_recovery"><button class="button">'.esc_html__('Dismiss this notice','wordpress-news-bot').'</button></form><p></p></div>';}

        if($sourceHealth['ready']&&$deleteId){
            $source=(array)$wpdb->get_row($wpdb->prepare('SELECT * FROM '.Support::table('sources').' WHERE id=%d LIMIT 1',$deleteId),ARRAY_A);
            if($source){$summary=(new SourceService($wpdb))->deletionSummary($deleteId);echo '<div class="wpnb-card"><h2>'.esc_html__('Delete news source','wordpress-news-bot').'</h2><p><strong>'.esc_html__('Are you sure you want to delete this news source?','wordpress-news-bot').'</strong></p><p>'.esc_html(sprintf(__('Pending news: %d','wordpress-news-bot'),$summary['pending'])).'<br>'.esc_html(sprintf(__('Processed news: %d','wordpress-news-bot'),$summary['processed'])).'<br>'.esc_html(sprintf(__('Created WordPress drafts: %d','wordpress-news-bot'),$summary['drafts'])).'</p><p>'.esc_html__('Existing WordPress posts and drafts will not be deleted.','wordpress-news-bot').'</p><div class="wpnb-actions"><form method="post" action="'.esc_url(admin_url('admin-post.php')).'">';wp_nonce_field('wpnb_delete_source_'.$deleteId);echo '<input type="hidden" name="action" value="wpnb_delete_source"><input type="hidden" name="source_id" value="'.esc_attr((string)$deleteId).'"><button class="button button-primary wpnb-danger">'.esc_html__('Delete','wordpress-news-bot').'</button></form><a class="button" href="'.esc_url(admin_url('admin.php?page=wpnb-sources')).'">'.esc_html__('Cancel','wordpress-news-bot').'</a></div></div>';}
        }

        echo '<form id="wpnb-bulk-form" method="post" action="'.esc_url(admin_url('admin-post.php')).'" class="wpnb-actions" style="margin:12px 0">';wp_nonce_field('wpnb_bulk_sources');echo '<input type="hidden" name="action" value="wpnb_bulk_sources"><label class="screen-reader-text" for="wpnb-bulk-action">'.esc_html__('Bulk actions','wordpress-news-bot').'</label><select id="wpnb-bulk-action" name="bulk_action" required><option value="">'.esc_html__('Bulk actions','wordpress-news-bot').'</option><option value="activate">'.esc_html__('Activate','wordpress-news-bot').'</option><option value="deactivate">'.esc_html__('Deactivate','wordpress-news-bot').'</option><option value="delete">'.esc_html__('Delete','wordpress-news-bot').'</option></select><button class="button" onclick="if(this.form.bulk_action.value===\'delete\'&&!confirm(\''.esc_js(__('Are you sure you want to delete the selected news sources?','wordpress-news-bot')).'\'))return false;">'.esc_html__('Apply','wordpress-news-bot').'</button></form>';
        echo '<table class="widefat striped wpnb-sources-table"><thead><tr><td class="check-column"><input type="checkbox" onclick="document.querySelectorAll(\'.wpnb-source-check\').forEach(e=>e.checked=this.checked)"></td><th>'.esc_html__('Source name','wordpress-news-bot').'</th><th>'.esc_html__('RSS/Atom URL','wordpress-news-bot').'</th><th>'.esc_html__('Allowed domain','wordpress-news-bot').'</th><th>'.esc_html__('Linked category','wordpress-news-bot').'</th><th>'.esc_html__('Status','wordpress-news-bot').'</th><th>'.esc_html__('Last check','wordpress-news-bot').'</th><th>'.esc_html__('Result','wordpress-news-bot').'</th><th>'.esc_html__('Actions','wordpress-news-bot').'</th></tr></thead><tbody>';
        if(!$rows)echo '<tr><td colspan="9">'.esc_html__('No news sources have been added yet.','wordpress-news-bot').'</td></tr>';
        foreach($rows as$row){$id=(int)$row->id;$category=$row->category_id?get_cat_name((int)$row->category_id):__('Unassigned','wordpress-news-bot');echo '<tr><th class="check-column"><input class="wpnb-source-check" form="wpnb-bulk-form" type="checkbox" name="source_ids[]" value="'.esc_attr((string)$id).'"></th><td data-label="'.esc_attr__('Source name','wordpress-news-bot').'">'.esc_html($row->name).'</td><td class="wpnb-source-url" data-label="'.esc_attr__('RSS/Atom URL','wordpress-news-bot').'">'.esc_html($row->feed_url).'</td><td data-label="'.esc_attr__('Allowed domain','wordpress-news-bot').'">'.nl2br(esc_html((string)$row->allowed_domains)).'</td><td data-label="'.esc_attr__('Linked category','wordpress-news-bot').'">'.esc_html($category).'</td><td data-label="'.esc_attr__('Status','wordpress-news-bot').'">'.esc_html($row->active?__('Active','wordpress-news-bot'):__('Inactive','wordpress-news-bot')).'</td><td data-label="'.esc_attr__('Last check','wordpress-news-bot').'">'.esc_html($row->last_checked_at?:__('Never','wordpress-news-bot')).'</td><td data-label="'.esc_attr__('Result','wordpress-news-bot').'">'.esc_html($row->last_result?:($row->last_error?:__('Not tested','wordpress-news-bot'))).'</td><td data-label="'.esc_attr__('Actions','wordpress-news-bot').'"><div class="wpnb-source-actions">';
            $this->sourceActionForm('wpnb_test_source','wpnb_test_source_'.$id,$id,__('Test','wordpress-news-bot'));
            echo '<a class="button" href="'.esc_url(admin_url('admin.php?page=wpnb-sources&wpnb_edit='.$id.'#wpnb-source-form')).'">'.esc_html__('Edit','wordpress-news-bot').'</a>';
            $this->sourceActionForm('wpnb_toggle_source','wpnb_toggle_source_'.$id,$id,$row->active?__('Deactivate','wordpress-news-bot'):__('Activate','wordpress-news-bot'));
            echo '<a class="button wpnb-danger" href="'.esc_url(admin_url('admin.php?page=wpnb-sources&wpnb_delete_confirm='.$id)).'">'.esc_html__('Delete','wordpress-news-bot').'</a></div></td></tr>';
        }
        echo '</tbody></table><div id="wpnb-source-form" class="wpnb-card" style="margin-top:20px"><h2>'.esc_html(!empty($edit['id'])?__('Edit source','wordpress-news-bot'):__('Add source','wordpress-news-bot')).'</h2>';if(!empty($formState['result']))$this->sourceTestResult((array)$formState['result']);$this->sourceForm(false,$edit,(string)($formState['token']??''));echo '</div>';$this->end();
    }
    private function sourceActionForm(string$action,string$nonce,int$id,string$label):void { echo '<form method="post" action="'.esc_url(admin_url('admin-post.php')).'">';wp_nonce_field($nonce);echo '<input type="hidden" name="action" value="'.esc_attr($action).'"><input type="hidden" name="source_id" value="'.esc_attr((string)$id).'"><button class="button">'.esc_html($label).'</button></form>'; }
    private function sourceForm(bool$wizard,array$source=[],string$testToken=''):void
    {
        $id=(int)($source['id']??0);$active=$source?(!empty($source['active'])):true;
        $feedUrl=(string)($source['feed_url']??'');$parts=$feedUrl!==''?wp_parse_url($feedUrl):[];$primaryHost=SourceUrl::normalizeHost((string)($parts['host']??''));$automaticHosts=[$primaryHost];if(str_starts_with($primaryHost,'www.')&&count(explode('.',substr($primaryHost,4)))>=3)$automaticHosts[]=substr($primaryHost,4);$advancedDomains=array_values(array_diff(array_filter(array_map('trim',preg_split('/[\r\n,]+/',(string)($source['allowed_domains']??''))?:[])),$automaticHosts));
        echo '<form method="post" action="'.esc_url(admin_url('admin-post.php')).'">';wp_nonce_field('wpnb_save_source');echo '<input type="hidden" name="source_id" value="'.esc_attr((string)$id).'"><input type="hidden" name="return_page" value="'.esc_attr($wizard?'wpnb-setup':'wpnb-sources').'"><input type="hidden" name="source_test_token" value="'.esc_attr($testToken).'">';
        echo '<div class="wpnb-field"><label for="wpnb-source-name">'.esc_html__('Source name','wordpress-news-bot').'</label><input id="wpnb-source-name" required name="name" value="'.esc_attr((string)($source['name']??'')).'" class="regular-text"></div>';
        echo '<div class="wpnb-field"><label for="wpnb-feed-url">'.esc_html__('RSS/Atom URL','wordpress-news-bot').'</label><input id="wpnb-feed-url" required type="url" name="feed_url" value="'.esc_attr($feedUrl).'" placeholder="https://example.com/feed" class="regular-text"></div>';
        echo '<details class="wpnb-field"><summary><strong>'.esc_html__('Advanced Settings','wordpress-news-bot').'</strong></summary><p><label for="wpnb-allowed-domains">'.esc_html__('Additional redirect domains','wordpress-news-bot').'</label><input id="wpnb-allowed-domains" name="allowed_domains" value="'.esc_attr(implode("\n",$advancedDomains)).'" placeholder="cdn.example.com" class="regular-text"></p><p class="description">'.esc_html__('The primary allowed host is detected automatically from the RSS URL. Add only extra trusted redirect domains here.','wordpress-news-bot').'</p></details>';
        echo '<div class="wpnb-field"><label for="wpnb-category">'.esc_html__('WordPress category','wordpress-news-bot').'</label>';wp_dropdown_categories(['id'=>'wpnb-category','name'=>'category_id','show_option_none'=>__('Unassigned','wordpress-news-bot'),'option_none_value'=>'0','hide_empty'=>0,'selected'=>(int)($source['category_id']??0)]);echo '</div>';
        echo '<div class="wpnb-field"><label><input type="checkbox" name="active" value="1" '.checked($active,true,false).'> '.esc_html__('Active','wordpress-news-bot').'</label></div><div class="wpnb-actions"><button class="button" name="action" value="wpnb_test_source">'.esc_html__('Test Before Saving','wordpress-news-bot').'</button><button class="button button-primary" name="action" value="wpnb_save_source">'.esc_html($id?__('Update Source','wordpress-news-bot'):__('Save Source','wordpress-news-bot')).'</button></div></form>';
    }
    public function saveSource():void { $this->requirePostAction('wpnb_save_source');global$wpdb;$id=absint($_POST['source_id']??0);$input=$this->sourceInput();try{$verified=$this->verifiedSourceTest($input);(new SourceService($wpdb))->save($input,$id,$verified);delete_transient($this->sourceFormKey());delete_option('wpnb_source_recovery_required');delete_user_meta(get_current_user_id(),'wpnb_source_recovery_ack');$return=sanitize_key($_POST['return_page']??'wpnb-sources');$this->redirect($return==='wpnb-setup'?'wpnb-setup&step=5':'wpnb-sources',$id?'source_updated':'source_saved');}catch(\DomainException$e){$this->retainSourceForm($input);$this->logSourceError('source_save_duplicate',$e);$this->redirect('wpnb-sources','source_duplicate');}catch(SourceTestException$e){$this->retainSourceForm($input);$this->handleSourceDiagnostic($e,'source_save_failed');}catch(\Throwable$e){$this->retainSourceForm($input);$this->logSourceError('source_save_failed',$e);$this->redirect('wpnb-sources','source_error');} }
    public function testSource():void { $id=absint($_POST['source_id']??0);$this->requirePostAction($id?'wpnb_test_source_'.$id:'wpnb_save_source');global$wpdb;$input=$id?(array)$wpdb->get_row($wpdb->prepare('SELECT * FROM '.Support::table('sources').' WHERE id=%d LIMIT 1',$id),ARRAY_A):$this->sourceInput();try{$result=(new SourceService($wpdb))->testConnection($input);$detail=sprintf(__('HTTP %1$d, %2$s, %3$d accessible items, %4$d ms','wordpress-news-bot'),$result['http_status'],$result['feed_type'],$result['item_count'],$result['duration_ms']);if(!$id){$token=bin2hex(random_bytes(16));set_transient($this->sourceFormKey(),['input'=>$input,'result'=>$result,'token'=>$token,'input_hash'=>hash('sha256',Support::json($input))],10*MINUTE_IN_SECONDS);}$wpdb->insert(Support::table('logs'),['level'=>'info','event'=>'source_test_succeeded','message'=>'A source connection test succeeded.','context_json'=>Support::json(Security::cleanLogContext($result)),'created_at'=>Support::now()]);$this->storeAdminNotice($detail);if($id)$wpdb->update(Support::table('sources'),['last_checked_at'=>Support::now(),'last_result'=>$detail,'last_error'=>null,'updated_at'=>Support::now()],['id'=>$id]);$this->redirect('wpnb-sources','source_tested');}catch(SourceTestException$e){if(!$id)$this->retainSourceForm($input);if($id)$wpdb->update(Support::table('sources'),['last_checked_at'=>Support::now(),'last_result'=>__('Failed','wordpress-news-bot'),'last_error'=>$this->sourceErrorMessage($e->resultCode),'updated_at'=>Support::now()],['id'=>$id]);$this->handleSourceDiagnostic($e,'source_test_failed');}catch(\Throwable$e){if(!$id)$this->retainSourceForm($input);$this->logSourceError('source_test_failed',$e);$this->redirect('wpnb-sources','source_error');} }
    public function dismissRecovery():void { $this->requirePostAction('wpnb_dismiss_recovery');$recovery=(array)get_option('wpnb_source_recovery_required',[]);if($recovery)update_user_meta(get_current_user_id(),'wpnb_source_recovery_ack',hash('sha256',Support::json($recovery)));$this->redirect('wpnb-sources'); }
    public function toggleSource():void { $id=absint($_POST['source_id']??0);$this->requirePostAction('wpnb_toggle_source_'.$id);global$wpdb;try{(new SourceService($wpdb))->toggle($id);$this->redirect('wpnb-sources','source_toggled');}catch(\Throwable$e){$this->logSourceError('source_toggle_failed',$e);$this->redirect('wpnb-sources','source_error');} }
    public function deleteSource():void { $id=absint($_POST['source_id']??0);$this->requirePostAction('wpnb_delete_source_'.$id);global$wpdb;try{(new SourceService($wpdb))->delete($id);$this->redirect('wpnb-sources','source_deleted');}catch(\Throwable$e){$this->logSourceError('source_delete_failed',$e);$this->redirect('wpnb-sources','source_error');} }
    public function bulkSources():void { $this->requirePostAction('wpnb_bulk_sources');global$wpdb;$ids=array_slice(array_values(array_filter(array_map('absint',(array)($_POST['source_ids']??[])))),0,100);$operation=sanitize_key($_POST['bulk_action']??'');if(!in_array($operation,['activate','deactivate','delete'],true)||!$ids){$this->redirect('wpnb-sources','source_error');}$service=new SourceService($wpdb);try{foreach($ids as$id){if($operation==='delete')$service->delete($id);else$service->toggle($id,$operation==='activate');}$this->redirect('wpnb-sources','bulk_done');}catch(\Throwable$e){$this->logSourceError('source_bulk_failed',$e);$this->redirect('wpnb-sources','source_error');} }
    private function sourceInput():array { return ['name'=>wp_unslash($_POST['name']??''),'feed_url'=>wp_unslash($_POST['feed_url']??''),'allowed_domains'=>wp_unslash($_POST['allowed_domains']??''),'category_id'=>absint($_POST['category_id']??0),'active'=>empty($_POST['active'])?0:1]; }
    public function pool():void { global$wpdb;$rows=$wpdb->get_results('SELECT id,title,source_url,status FROM '.Support::table('feed_items').' ORDER BY id DESC LIMIT 100');$this->begin(__('News Pool','wordpress-news-bot'));$this->notice();if(!$rows){echo '<div class="wpnb-card"><p>'.esc_html__('No news items are waiting for review.','wordpress-news-bot').'</p></div>';$this->end();return;}echo '<form method="post" action="'.esc_url(admin_url('admin-post.php')).'">';wp_nonce_field('wpnb_bulk_create_drafts');echo '<input type="hidden" name="action" value="wpnb_bulk_create_drafts"><table class="widefat striped"><thead><tr><th class="check-column"></th><th>'.esc_html__('Title','wordpress-news-bot').'</th><th>'.esc_html__('Status','wordpress-news-bot').'</th><th>'.esc_html__('Actions','wordpress-news-bot').'</th></tr></thead><tbody>';foreach($rows as$row){$eligible=in_array((string)$row->status,['new','review','error'],true);echo '<tr><th class="check-column">'.($eligible?'<input type="checkbox" name="item_ids[]" value="'.esc_attr((string)$row->id).'">':'').'</th><td><a href="'.esc_url((string)$row->source_url).'" target="_blank" rel="noopener noreferrer">'.esc_html((string)$row->title).'</a></td><td>'.esc_html((string)$row->status).'</td><td>';if($eligible){wp_nonce_field('wpnb_create_draft_'.(int)$row->id,'_wpnonce_'.(int)$row->id);echo '<button class="button wpnb-create-draft" type="submit" name="single_item_id" value="'.esc_attr((string)$row->id).'">'.esc_html__('Create Draft','wordpress-news-bot').'</button>';}echo '</td></tr>';}echo '</tbody></table><p><button class="button button-primary" type="submit">'.esc_html__('Create Selected Drafts','wordpress-news-bot').'</button></p></form>';$this->end(); }
    public function health():void { $this->requireManage();global$wpdb;$report=(new DatabaseHealth($wpdb))->inspect();$this->begin(__('System Health','wordpress-news-bot'));$this->notice();echo '<p>'.esc_html((new SecretStorage())->isSupported()?__('Secure encryption is available.','wordpress-news-bot'):__('Secure encryption is unavailable. API keys cannot be stored.','wordpress-news-bot')).'</p><div class="wpnb-card"><h2>'.esc_html__('Database Health','wordpress-news-bot').'</h2><p class="wpnb-status">'.esc_html($report['status']==='healthy'?__('Healthy','wordpress-news-bot'):__('Repair required','wordpress-news-bot')).'</p><p>'.esc_html(sprintf(__('Schema fingerprint: %s','wordpress-news-bot'),$report['fingerprint'])).'<br>'.esc_html(sprintf(__('Plugin/schema version: %1$s / %2$s','wordpress-news-bot'),WPNB_VERSION,WPNB_SCHEMA_VERSION)).'</p>';
        $engineIssues=array_values(array_filter($report['issues'],static fn(array$issue):bool=>($issue['code']??'')==='engine_mismatch'));$enginePreview=$engineIssues?(new DatabaseEngineRepair($wpdb))->preview():[];
        if($report['issues']){echo '<ul>';foreach($report['issues']as$issue)echo '<li>'.esc_html($this->healthIssue($issue)).'</li>';echo '</ul>';if($engineIssues){echo '<div class="notice notice-warning inline"><p><strong>'.esc_html__('WordPress News Bot tables will be converted from MyISAM to InnoDB. Existing data will be preserved. Only plugin tables will be affected.','wordpress-news-bot').'</strong></p><p>'.esc_html(sprintf(__('Preflight: %1$s, rows: %2$d, estimated size: %3$s','wordpress-news-bot'),$this->engineErrorMessage((string)$enginePreview['code']),(int)$enginePreview['total_rows'],size_format((int)$enginePreview['total_bytes']))).'</p></div>';}echo '<form method="post" action="'.esc_url(admin_url('admin-post.php')).'">';wp_nonce_field('wpnb_repair_database');echo '<input type="hidden" name="action" value="wpnb_repair_database">';if($engineIssues)echo '<p><label><input type="checkbox" name="confirm_engine_conversion" value="1" required> '.esc_html__('I confirm the MyISAM to InnoDB conversion for WordPress News Bot tables.','wordpress-news-bot').'</label></p>';echo '<button class="button button-primary" '.($engineIssues&&in_array($enginePreview['code'],['innodb_unavailable','alter_permission_denied'],true)?'disabled':'').'>'.esc_html__('Repair Database','wordpress-news-bot').'</button></form>';}else{$pendingSource=(array)get_transient($this->sourceFormKey());if(!empty($pendingSource['token']))echo '<p><a class="button button-primary" href="'.esc_url(admin_url('admin.php?page=wpnb-sources#wpnb-source-form')).'">'.esc_html__('Return to the verified source and save it','wordpress-news-bot').'</a></p>';}
        $safeReport=['status'=>$report['status'],'issues'=>$report['issues'],'schema_fingerprint'=>$report['fingerprint'],'plugin_version'=>WPNB_VERSION,'stored_schema'=>$report['stored_schema'],'expected_schema'=>$report['expected_schema'],'engine_preflight'=>$enginePreview,'engine_repair_state'=>DatabaseEngineRepair::state(),'generated_at'=>Support::now()];echo '<p><button type="button" class="button" onclick="navigator.clipboard.writeText(document.getElementById(\'wpnb-diagnostic-report\').value)">'.esc_html__('Copy Diagnostic Information','wordpress-news-bot').'</button></p><textarea id="wpnb-diagnostic-report" class="large-text code" rows="8" readonly>'.esc_textarea(Support::json($safeReport)).'</textarea></div>';
        $testId=sanitize_text_field(wp_unslash($_GET['test_id']??''));echo '<div class="wpnb-card"><h2>'.esc_html__('Diagnostics','wordpress-news-bot').'</h2><form method="get"><input type="hidden" name="page" value="wpnb-health"><label for="wpnb-test-id">'.esc_html__('Test ID','wordpress-news-bot').'</label> <input id="wpnb-test-id" name="test_id" value="'.esc_attr($testId).'" pattern="[a-fA-F0-9]{16,64}"> <button class="button">'.esc_html__('Search','wordpress-news-bot').'</button></form>';
        if($testId!==''){$record=DiagnosticStore::find($testId);if($record&&($record['db_code']??'')==='db_unknown'&&($record['operation']??'')==='schema_repair'&&$engineIssues){$record['db_code']='engine_conversion_required';$record['suggestion']=__('MyISAM to InnoDB conversion is required. Confirm and run Database Repair.','wordpress-news-bot');}if($record)echo '<pre>'.esc_html(Support::json($record)).'</pre>';else echo '<p>'.esc_html__('No safe diagnostic record was found for this Test ID.','wordpress-news-bot').'</p>';}echo '</div>';$this->automationCard();$this->end(); }
    public function repairDatabase():void { $this->requirePostAction('wpnb_repair_database');global$wpdb;$testId=bin2hex(random_bytes(8));$preview=(new DatabaseEngineRepair($wpdb))->preview();$approved=!empty($_POST['confirm_engine_conversion']);try{if($preview['code']==='engine_conversion_required'&&!$approved)throw new DatabaseEngineRepairException('engine_conversion_required',['suggestion'=>'Confirm the MyISAM to InnoDB conversion.']);$result=(new DatabaseRepair($wpdb))->run(false,$approved);if($result['status']!=='healthy'){DiagnosticStore::record($testId,'database',$result['code'],'schema_repair',['schema_fingerprint'=>$result['after'],'affected_rows'=>$result['changed'],'suggestion'=>'Review unresolved schema issues before retrying.']);$this->storeAdminNotice(sprintf(__('Test ID: %s','wordpress-news-bot'),$testId));$this->redirect('wpnb-health&test_id='.$testId,'db_repair_failed');}$this->redirect('wpnb-health','db_repaired');}catch(DatabaseEngineRepairException$e){DiagnosticStore::record($testId,'database',$e->resultCode,'schema_repair',$e->diagnostics+['schema_fingerprint'=>(new DatabaseHealth($wpdb))->inspect()['fingerprint']]);$this->storeAdminNotice($this->engineErrorMessage($e->resultCode).' '.sprintf(__('Test ID: %s','wordpress-news-bot'),$testId));$this->redirect('wpnb-health&test_id='.$testId,'db_repair_failed');}catch(\Throwable$e){$classified=DatabaseErrorClassifier::classify((string)($wpdb->last_error??''),(int)($wpdb->last_errno??0));DiagnosticStore::record($testId,'database',$classified['code'],'schema_repair',$classified+['schema_fingerprint'=>(new DatabaseHealth($wpdb))->inspect()['fingerprint']]);$this->storeAdminNotice(sprintf(__('Test ID: %s','wordpress-news-bot'),$testId));$this->redirect('wpnb-health&test_id='.$testId,'db_repair_failed');} }
    public function saveAndTestOpenAi():void { $this->requirePostAction('wpnb_save_test_openai');$key=trim((string)wp_unslash($_POST['api_key']??''));$model=sanitize_text_field(wp_unslash($_POST['model']??'gpt-4o-mini'));$return=sanitize_key($_POST['return_page']??'wpnb-settings');if(!in_array($return,['wpnb-settings','wpnb-setup'],true))$return='wpnb-settings';try{$result=(new ConnectionService(new SecretStorage()))->saveAndTest($key,$model);$s=$this->settingsValue();$s['ai_model']=$model;$s['ai_provider']='openai';update_option('wpnb_settings',$s,false);$this->saveStatus($result);$this->redirect($return,'saved');}catch(\Throwable){$this->redirect($return,'error');} }
    public function retestOpenAi():void { $this->requirePostAction('wpnb_retest_openai');try{$result=(new ConnectionService(new SecretStorage()))->retest((string)($this->settingsValue()['ai_model']??'gpt-4o-mini'));$this->saveStatus($result);$this->redirect('wpnb-settings','tested');}catch(\Throwable$e){$this->redirect('wpnb-settings',str_contains($e->getMessage(),'şifresi')?'decrypt':'error');} }
    public function deleteOpenAi():void { $this->requirePostAction('wpnb_delete_openai');(new ConnectionService(new SecretStorage()))->delete();update_option('wpnb_connection_status',['connected'=>0],false);$this->redirect('wpnb-settings','deleted'); }
    private function saveStatus(array$result):void { update_option('wpnb_connection_status',['connected'=>1,'tested_at'=>current_time('mysql'),'model'=>sanitize_text_field($result['model']),'duration_ms'=>(int)$result['duration_ms'],'request_id'=>sanitize_text_field($result['request_id']),'http_class'=>(int)$result['http_class']],false); }
    public function skipSetup():void { $this->requirePostAction('wpnb_skip_setup');update_option('wpnb_setup_state',SetupState::skipped(),false);$this->redirect('wpnb-dashboard'); }
    public function finishSetup():void { $this->requirePostAction('wpnb_finish_setup');update_option('wpnb_setup_state',SetupState::completed(),false);$this->redirect('wpnb-dashboard'); }
    public function manualRun():void { $this->requirePostAction('wpnb_manual_run');do_action('wpnb_sources_polled',true);update_option('wpnb_last_automation_run',Support::now(),false);$this->redirect('wpnb-settings'); }
    public function createDraft():void { $id=absint($_POST['item_id']??0);$this->requireReviewPostAction('wpnb_create_draft_'.$id);try{(new DraftService())->create($id);$this->redirect('wpnb-pool','draft_created');}catch(\Throwable){$this->redirect('wpnb-pool','draft_error');} }
    public function bulkCreateDrafts():void { $this->requireReviewPostAction('wpnb_bulk_create_drafts');$single=absint($_POST['single_item_id']??0);$ids=$single?[$single]:array_values(array_filter(array_map('absint',(array)($_POST['item_ids']??[]))));$limit=max(1,min(50,(int)($this->settingsValue()['max_run_items']??5)));$created=0;foreach(array_slice($ids,0,$limit)as$id)try{(new DraftService())->create($id);$created++;}catch(\Throwable){}$this->redirect('wpnb-pool',$created>0?'draft_created':'draft_error'); }
    private function requireManage():void { if(!Security::canManage())wp_die(esc_html__('You do not have permission to access this page.','wordpress-news-bot')); }
    private function requirePostAction(string$nonce):void { if(strtoupper((string)($_SERVER['REQUEST_METHOD']??''))!=='POST')wp_die(esc_html__('This action only accepts POST requests.','wordpress-news-bot'));$this->requireAction($nonce); }
    private function requireReviewPostAction(string$nonce):void { if(strtoupper((string)($_SERVER['REQUEST_METHOD']??''))!=='POST'||!Security::canReview()||!check_admin_referer($nonce))wp_die(esc_html__('Invalid request.','wordpress-news-bot')); }
    private function requireAction(string$nonce):void { $this->requireManage();if(!check_admin_referer($nonce))wp_die(esc_html__('Invalid security token.','wordpress-news-bot')); }
    private function storeAdminNotice(string$message):void { set_transient('wpnb_admin_notice_'.get_current_user_id(),sanitize_text_field($message),MINUTE_IN_SECONDS); }
    private function sourceFormKey():string { return 'wpnb_source_form_'.get_current_user_id(); }
    private function retainSourceForm(array$input):void { $input['id']=absint($_POST['source_id']??0);$state=(array)get_transient($this->sourceFormKey());$candidate=$input;$hashInput=$input;unset($hashInput['id']);if(!isset($state['input_hash'])||!hash_equals((string)$state['input_hash'],hash('sha256',Support::json($hashInput))))$state=[];$state['input']=$candidate;set_transient($this->sourceFormKey(),$state,10*MINUTE_IN_SECONDS); }
    private function verifiedSourceTest(array$input):?array { $state=(array)get_transient($this->sourceFormKey());$posted=sanitize_text_field(wp_unslash($_POST['source_test_token']??''));if($posted===''||empty($state['token'])||!hash_equals((string)$state['token'],$posted)||!hash_equals((string)($state['input_hash']??''),hash('sha256',Support::json($input))))return null;return isset($state['result'])&&is_array($state['result'])?$state['result']:null; }
    private function sourceTestResult(array$result):void { $latest=(string)($result['last_item_date']??'');echo '<div class="notice notice-success inline"><p><strong>'.esc_html__('Connection test succeeded.','wordpress-news-bot').'</strong><br>'.esc_html(sprintf(__('Feed type: %s','wordpress-news-bot'),$result['feed_type']??'')).'<br>'.esc_html(sprintf(__('Items found: %d','wordpress-news-bot'),(int)($result['item_count']??0))).'<br>'.esc_html(sprintf(__('Latest item date: %s','wordpress-news-bot'),$latest!==''?$latest:__('Not provided','wordpress-news-bot'))).'<br>'.esc_html(sprintf(__('HTTP status: %d','wordpress-news-bot'),(int)($result['http_status']??0))).'<br>'.esc_html(sprintf(__('Response time: %d ms','wordpress-news-bot'),(int)($result['duration_ms']??0))).'<br>'.esc_html(sprintf(__('Final host: %s','wordpress-news-bot'),$result['final_host']??'')).'</p></div>'; }
    private function sourceErrorMessage(string$code):string { return match($code){'url_invalid','host_invalid','dns_failed','ip_blocked','redirect_blocked'=>__('The source did not pass the security check. Check the RSS URL and redirect domains.','wordpress-news-bot'),'http_failed'=>__('The source server could not be reached. Please try again.','wordpress-news-bot'),'http_status_invalid'=>__('The source returned an invalid HTTP response.','wordpress-news-bot'),'content_type_invalid','feed_invalid'=>__('The response is not in RSS/Atom format.','wordpress-news-bot'),'body_empty'=>__('The source returned an empty response.','wordpress-news-bot'),'body_too_large'=>__('The source response is too large.','wordpress-news-bot'),'xml_invalid'=>__('The source XML could not be parsed.','wordpress-news-bot'),'database_schema_invalid'=>__('The physical database schema requires repair before this source can be saved.','wordpress-news-bot'),'database_failed'=>__('The source could not be saved to the database.','wordpress-news-bot'),default=>__('The source could not be processed. Check the RSS URL and try again.','wordpress-news-bot')}; }
    private function handleSourceDiagnostic(SourceTestException$e,string$event):never { $this->logSourceError($event,$e);$this->storeAdminNotice($this->sourceErrorMessage($e->resultCode).' '.sprintf(__('Test ID: %s','wordpress-news-bot'),$e->testId));if(in_array($e->resultCode,['database_schema_invalid','database_failed'],true))$this->redirect('wpnb-health&test_id='.$e->testId,'db_repair_required');$this->redirect('wpnb-sources','source_diagnostic_error'); }
    private function logSourceError(string$event,\Throwable$e):void { global$wpdb;$context=['exception_class'=>get_class($e),'error_code'=>(int)$e->getCode()];if($e instanceof SourceTestException){$context+=['result_code'=>$e->resultCode,'test_id'=>$e->testId]+$e->diagnostics;if(in_array($e->resultCode,['database_schema_invalid','database_failed'],true))DiagnosticStore::record($e->testId,'database',(string)($e->diagnostics['db_code']??'db_unknown'),(string)($e->diagnostics['operation']??'source_write'),$e->diagnostics);}$wpdb->insert(Support::table('logs'),['level'=>'error','event'=>$event,'message'=>'A source administration operation failed.','context_json'=>Support::json(Security::cleanLogContext($context)),'created_at'=>Support::now()]); }
    private function healthIssue(array$issue):string { $label=match((string)($issue['code']??'')){'table_missing'=>__('A plugin database table is missing.','wordpress-news-bot'),'column_missing'=>__('A required database column is missing.','wordpress-news-bot'),'column_type_mismatch','column_nullability_mismatch','column_default_mismatch','column_extra_mismatch'=>__('A database column definition does not match.','wordpress-news-bot'),'index_missing'=>__('A required database index is missing.','wordpress-news-bot'),'index_mismatch'=>__('A database index definition does not match.','wordpress-news-bot'),'engine_mismatch'=>__('A plugin table is not using InnoDB.','wordpress-news-bot'),'collation_mismatch'=>__('A plugin table charset or collation does not match WordPress.','wordpress-news-bot'),'schema_version_mismatch'=>__('The recorded schema version does not match.','wordpress-news-bot'),default=>__('Database metadata could not be verified.','wordpress-news-bot')};$parts=[$label];foreach(['table','column','index']as$key)if(isset($issue[$key]))$parts[]=sanitize_key((string)$issue[$key]);return implode(' | ',$parts); }
    private function engineErrorMessage(string$code):string{return match($code){'innodb_unavailable'=>__('InnoDB is not available on this database server. Contact your hosting provider.','wordpress-news-bot'),'alter_permission_denied'=>__('The WordPress database user does not have permission to convert plugin tables.','wordpress-news-bot'),'engine_conversion_required'=>__('Confirm the MyISAM to InnoDB conversion before continuing.','wordpress-news-bot'),'engine_conversion_failed'=>__('The engine conversion stopped safely at the first failed table. Run repair again after resolving the reported condition.','wordpress-news-bot'),default=>__('Database engine repair could not be completed.','wordpress-news-bot')};}
    private function takeAdminNotice():string { $key='wpnb_admin_notice_'.get_current_user_id();$message=(string)get_transient($key);delete_transient($key);return $message; }
    private function redirect(string$page,string$notice=''):never { $url=admin_url('admin.php?page='.$page.($notice?'&wpnb_notice='.$notice:''));wp_safe_redirect($url);exit; }
}
