<?php
declare(strict_types=1);
namespace WordPressNewsBot;

final class ImageImportService
{
    private const MIMES=['image/jpeg','image/png','image/webp'];
    public function __construct(private readonly?RemoteAssetFetcher$fetcher=null,private readonly?object$db=null){}

    /** @return array{status:string,attachment_id:int,error_code:string} */
    public function import(int$itemId):array
    {
        global$wpdb;$db=$this->db??$wpdb;$lock='wpnb_image_lock_'.$itemId;if(!add_option($lock,time(),'','no')){$created=(int)get_option($lock,0);if($created<1||$created>=time()-5*MINUTE_IN_SECONDS)return['status'=>'error','attachment_id'=>0,'error_code'=>'locked'];delete_option($lock);if(!add_option($lock,time(),'','no'))return['status'=>'error','attachment_id'=>0,'error_code'=>'locked'];}
        try{$item=$db->get_row($db->prepare('SELECT f.*,s.import_images,s.use_og_image,s.allowed_domains FROM '.Support::table('feed_items').' f JOIN '.Support::table('sources').' s ON s.id=f.source_id WHERE f.id=%d LIMIT 1',$itemId),ARRAY_A);if(!$item)return$this->result($db,$itemId,'error',0,'not_found');if(!(int)($item['import_images']??1))return$this->result($db,$itemId,'missing',0,'disabled');$existing=(int)($item['image_attachment_id']??0);if($existing>0&&get_post_type($existing)==='attachment')return$this->result($db,$itemId,'ready',$existing,'');
            $allowed=preg_split('/[\r\n,]+/',(string)($item['allowed_domains']??''))?:[];$url=trim((string)($item['image_url']??''));$source=(string)($item['image_source']??'');if($url===''&&!empty($item['use_og_image'])){[$url,$source]=$this->ogImage((string)$item['source_url'],$allowed);if($url!=='')$db->update(Support::table('feed_items'),['image_url'=>$url,'image_source'=>$source,'updated_at'=>Support::now()],['id'=>$itemId],['%s','%s','%s'],['%d']);}if($url==='')return$this->result($db,$itemId,'missing',0,'not_found');
            $urlHash=hash('sha256',SourceUrl::canonicalize($url));$byUrl=get_posts(['post_type'=>'attachment','post_status'=>'inherit','numberposts'=>1,'fields'=>'ids','meta_key'=>'_wpnb_source_image_url_hash','meta_value'=>$urlHash]);if($byUrl)return$this->attachExisting($db,$itemId,(int)$byUrl[0],$url);
            $settings=(array)get_option('wpnb_settings',[]);$max=max(65536,min(20*1024*1024,(int)($settings['image_max_bytes']??5242880)));$asset=($this->fetcher??new RemoteAssetFetcher())->fetch($url,$allowed,$max,self::MIMES);$minWidth=max(1,min(4000,(int)($settings['image_min_width']??300)));$minHeight=max(1,min(4000,(int)($settings['image_min_height']??200)));$validated=(new ImageValidator())->validate($asset['body'],$asset['content_type'],$minWidth,$minHeight);$hash=$validated['hash'];$byHash=get_posts(['post_type'=>'attachment','post_status'=>'inherit','numberposts'=>1,'fields'=>'ids','meta_key'=>'_wpnb_image_file_hash','meta_value'=>$hash]);if($byHash)return$this->attachExisting($db,$itemId,(int)$byHash[0],$url,$hash);
            $filename=sanitize_file_name('wpnb-'.$itemId.'-'.substr($hash,0,16).'.'.$validated['extension']);$temp=wp_tempnam($filename);if(!$temp||file_put_contents($temp,$asset['body'])!==strlen($asset['body']))throw new RemoteAssetException('temporary_file_failed');require_once ABSPATH.'wp-admin/includes/file.php';require_once ABSPATH.'wp-admin/includes/media.php';require_once ABSPATH.'wp-admin/includes/image.php';$attachmentId=media_handle_sideload(['name'=>$filename,'tmp_name'=>$temp,'type'=>$validated['mime']],0,'');if(is_wp_error($attachmentId)){@unlink($temp);throw new RemoteAssetException('media_save_failed');}$attachmentId=(int)$attachmentId;update_post_meta($attachmentId,'_wpnb_source_image_url',$url);update_post_meta($attachmentId,'_wpnb_source_image_url_hash',$urlHash);update_post_meta($attachmentId,'_wpnb_image_file_hash',$hash);update_post_meta($attachmentId,'_wpnb_feed_item_id',$itemId);update_post_meta($attachmentId,'_wp_attachment_image_alt','');wp_update_post(['ID'=>$attachmentId,'post_excerpt'=>'','post_content'=>'']);return$this->result($db,$itemId,'ready',$attachmentId,'',$hash);
        }catch(RemoteAssetException$e){return$this->result($db,$itemId,'error',0,$e->resultCode);}catch(\Throwable){return$this->result($db,$itemId,'error',0,'processing_failed');}finally{delete_option($lock);}
    }

    private function ogImage(string$articleUrl,array$allowed):array{try{$asset=($this->fetcher??new RemoteAssetFetcher())->fetch($articleUrl,$allowed,524288,['text/html','application/xhtml+xml']);$url='';if(preg_match('~<meta\b[^>]*(?:property|name)\s*=\s*(["\'])og:image\1[^>]*content\s*=\s*(["\'])(.*?)\2~isu',$asset['body'],$match))$url=(string)$match[3];elseif(preg_match('~<meta\b[^>]*content\s*=\s*(["\'])(.*?)\1[^>]*(?:property|name)\s*=\s*(["\'])og:image\3~isu',$asset['body'],$match))$url=(string)$match[2];$url=esc_url_raw(html_entity_decode($url,ENT_QUOTES|ENT_HTML5,'UTF-8'));if(preg_match('~^https://~i',$url))return[$url,'og:image'];}catch(\Throwable){}return['',''];}
    private function attachExisting(object$db,int$itemId,int$attachmentId,string$url,string$hash=''):array{update_post_meta($attachmentId,'_wpnb_feed_item_id',$itemId);if($hash==='')$hash=(string)get_post_meta($attachmentId,'_wpnb_image_file_hash',true);return$this->result($db,$itemId,'ready',$attachmentId,'',$hash);}
    private function result(object$db,int$itemId,string$status,int$attachmentId,string$errorCode,string$hash=''):array{$record=['image_status'=>$status,'image_attachment_id'=>$attachmentId,'image_hash'=>$hash,'image_error_code'=>$errorCode,'updated_at'=>Support::now()];$db->update(Support::table('feed_items'),$record,['id'=>$itemId],DatabaseSchema::formatsFor('feed_items',$record),['%d']);return['status'=>$status,'attachment_id'=>$attachmentId,'error_code'=>$errorCode];}
}
